/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformIndexRouteImport } from './routes/platform/index'
import { Route as PlatformOrganizationIdRouteImport } from './routes/platform/$organizationId'
import { Route as OauthInstagramRouteImport } from './routes/oauth/instagram'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as LoginEmailRouteImport } from './routes/login_.email'
import { Route as AuthWhatsappManagerRouteImport } from './routes/_auth/whatsapp-manager'
import { Route as AuthStatsRouteImport } from './routes/_auth/stats'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthQuickRepliesRouteImport } from './routes/_auth/quick-replies'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as PlatformOrganizationIdIndexRouteImport } from './routes/platform/$organizationId/index'
import { Route as AuthTemplatesIndexRouteImport } from './routes/_auth/templates/index'
import { Route as AuthTeamMembersIndexRouteImport } from './routes/_auth/team-members/index'
import { Route as AuthStatsIndexRouteImport } from './routes/_auth/stats/index'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthIntegrationsIndexRouteImport } from './routes/_auth/integrations/index'
import { Route as AuthConversationsIndexRouteImport } from './routes/_auth/conversations/index'
import { Route as AuthContactsIndexRouteImport } from './routes/_auth/contacts/index'
import { Route as AuthChatbotsIndexRouteImport } from './routes/_auth/chatbots/index'
import { Route as AuthCampaignsIndexRouteImport } from './routes/_auth/campaigns/index'
import { Route as AuthAgentsIndexRouteImport } from './routes/_auth/agents/index'
import { Route as PlatformOrganizationIdReportsRouteImport } from './routes/platform/$organizationId/reports'
import { Route as OnboardWhatsappTokenRouteImport } from './routes/onboard.whatsapp.$token'
import { Route as OnboardInstagramCallbackRouteImport } from './routes/onboard.instagram.callback'
import { Route as OnboardInstagramTokenRouteImport } from './routes/onboard.instagram.$token'
import { Route as AuthTemplatesNewRouteImport } from './routes/_auth/templates/new'
import { Route as AuthTemplatesTemplateIdRouteImport } from './routes/_auth/templates/$templateId'
import { Route as AuthStatsUsageRouteImport } from './routes/_auth/stats/usage'
import { Route as AuthStatsQuotasRouteImport } from './routes/_auth/stats/quotas'
import { Route as AuthSettingsRoutingQueuesRouteImport } from './routes/_auth/settings/routing-queues'
import { Route as AuthIntegrationsMediaPreprocessingRouteImport } from './routes/_auth/integrations/media-preprocessing'
import { Route as AuthConversationsNewRouteImport } from './routes/_auth/conversations/new'
import { Route as AuthContactsNewRouteImport } from './routes/_auth/contacts/new'
import { Route as AuthContactsContactIdRouteImport } from './routes/_auth/contacts/$contactId'
import { Route as AuthChatbotsFlowIdRouteImport } from './routes/_auth/chatbots/$flowId'
import { Route as AuthCampaignsNewRouteImport } from './routes/_auth/campaigns/new'
import { Route as AuthCampaignsCampaignIdRouteImport } from './routes/_auth/campaigns/$campaignId'
import { Route as AuthAgentsNewRouteImport } from './routes/_auth/agents/new'
import { Route as AuthAgentsAgentIdRouteImport } from './routes/_auth/agents/$agentId'
import { Route as AuthSettingsWebhooksIndexRouteImport } from './routes/_auth/settings/webhooks/index'
import { Route as AuthSettingsOrganizationIndexRouteImport } from './routes/_auth/settings/organization/index'
import { Route as AuthSettingsMembersIndexRouteImport } from './routes/_auth/settings/members/index'
import { Route as AuthSettingsApiKeysIndexRouteImport } from './routes/_auth/settings/api-keys/index'
import { Route as AuthIntegrationsWhatsappIndexRouteImport } from './routes/_auth/integrations/whatsapp/index'
import { Route as AuthIntegrationsInstagramIndexRouteImport } from './routes/_auth/integrations/instagram/index'
import { Route as AuthTemplatesTemplateIdEditRouteImport } from './routes/_auth/templates/$templateId.edit'
import { Route as AuthSettingsWebhooksNewRouteImport } from './routes/_auth/settings/webhooks/new'
import { Route as AuthSettingsWebhooksWebhookIdRouteImport } from './routes/_auth/settings/webhooks/$webhookId'
import { Route as AuthSettingsOrganizationNewRouteImport } from './routes/_auth/settings/organization/new'
import { Route as AuthSettingsMembersNewRouteImport } from './routes/_auth/settings/members/new'
import { Route as AuthSettingsMembersMemberIdRouteImport } from './routes/_auth/settings/members/$memberId'
import { Route as AuthSettingsApiKeysNewRouteImport } from './routes/_auth/settings/api-keys/new'
import { Route as AuthSettingsApiKeysApiKeyIdRouteImport } from './routes/_auth/settings/api-keys/$apiKeyId'
import { Route as AuthIntegrationsWhatsappNewRouteImport } from './routes/_auth/integrations/whatsapp/new'
import { Route as AuthIntegrationsInstagramNewRouteImport } from './routes/_auth/integrations/instagram/new'
import { Route as AuthCampaignsCampaignIdReviewRouteImport } from './routes/_auth/campaigns/$campaignId_.review'
import { Route as AuthCampaignsCampaignIdEditRouteImport } from './routes/_auth/campaigns/$campaignId_.edit'
import { Route as AuthIntegrationsWhatsappOnboardingIndexRouteImport } from './routes/_auth/integrations/whatsapp/onboarding/index'
import { Route as AuthIntegrationsWhatsappOrgAddressIdIndexRouteImport } from './routes/_auth/integrations/whatsapp/$orgAddressId/index'
import { Route as AuthIntegrationsInstagramOnboardingIndexRouteImport } from './routes/_auth/integrations/instagram/onboarding/index'
import { Route as AuthIntegrationsInstagramOrgAddressIdIndexRouteImport } from './routes/_auth/integrations/instagram/$orgAddressId/index'
import { Route as AuthIntegrationsWhatsappOnboardingNewRouteImport } from './routes/_auth/integrations/whatsapp/onboarding/new'
import { Route as AuthIntegrationsWhatsappOnboardingTokenIdRouteImport } from './routes/_auth/integrations/whatsapp/onboarding/$tokenId'
import { Route as AuthIntegrationsWhatsappOrgAddressIdProfileRouteImport } from './routes/_auth/integrations/whatsapp/$orgAddressId/profile'
import { Route as AuthIntegrationsInstagramOnboardingNewRouteImport } from './routes/_auth/integrations/instagram/onboarding/new'
import { Route as AuthIntegrationsInstagramOnboardingTokenIdRouteImport } from './routes/_auth/integrations/instagram/onboarding/$tokenId'
import { Route as AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRouteImport } from './routes/_auth/integrations/whatsapp/$orgAddressId/templates/index'
import { Route as AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRouteImport } from './routes/_auth/integrations/whatsapp/$orgAddressId/templates/new'
import { Route as AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRouteImport } from './routes/_auth/integrations/whatsapp/$orgAddressId/templates/$templateId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformOrganizationIdRoute = PlatformOrganizationIdRouteImport.update({
  id: '/$organizationId',
  path: '/$organizationId',
  getParentRoute: () => PlatformRoute,
} as any)
const OauthInstagramRoute = OauthInstagramRouteImport.update({
  id: '/oauth/instagram',
  path: '/oauth/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginEmailRoute = LoginEmailRouteImport.update({
  id: '/login_/email',
  path: '/login/email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWhatsappManagerRoute = AuthWhatsappManagerRouteImport.update({
  id: '/whatsapp-manager',
  path: '/whatsapp-manager',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStatsRoute = AuthStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthQuickRepliesRoute = AuthQuickRepliesRouteImport.update({
  id: '/quick-replies',
  path: '/quick-replies',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const PlatformOrganizationIdIndexRoute =
  PlatformOrganizationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PlatformOrganizationIdRoute,
  } as any)
const AuthTemplatesIndexRoute = AuthTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTeamMembersIndexRoute = AuthTeamMembersIndexRouteImport.update({
  id: '/team-members/',
  path: '/team-members/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStatsIndexRoute = AuthStatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthStatsRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthIntegrationsIndexRoute = AuthIntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConversationsIndexRoute = AuthConversationsIndexRouteImport.update({
  id: '/conversations/',
  path: '/conversations/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthContactsIndexRoute = AuthContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChatbotsIndexRoute = AuthChatbotsIndexRouteImport.update({
  id: '/chatbots/',
  path: '/chatbots/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCampaignsIndexRoute = AuthCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsIndexRoute = AuthAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AuthRoute,
} as any)
const PlatformOrganizationIdReportsRoute =
  PlatformOrganizationIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => PlatformOrganizationIdRoute,
  } as any)
const OnboardWhatsappTokenRoute = OnboardWhatsappTokenRouteImport.update({
  id: '/onboard/whatsapp/$token',
  path: '/onboard/whatsapp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardInstagramCallbackRoute =
  OnboardInstagramCallbackRouteImport.update({
    id: '/onboard/instagram/callback',
    path: '/onboard/instagram/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnboardInstagramTokenRoute = OnboardInstagramTokenRouteImport.update({
  id: '/onboard/instagram/$token',
  path: '/onboard/instagram/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTemplatesNewRoute = AuthTemplatesNewRouteImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTemplatesTemplateIdRoute = AuthTemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStatsUsageRoute = AuthStatsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthStatsRoute,
} as any)
const AuthStatsQuotasRoute = AuthStatsQuotasRouteImport.update({
  id: '/quotas',
  path: '/quotas',
  getParentRoute: () => AuthStatsRoute,
} as any)
const AuthSettingsRoutingQueuesRoute =
  AuthSettingsRoutingQueuesRouteImport.update({
    id: '/routing-queues',
    path: '/routing-queues',
    getParentRoute: () => AuthSettingsRoute,
  } as any)
const AuthIntegrationsMediaPreprocessingRoute =
  AuthIntegrationsMediaPreprocessingRouteImport.update({
    id: '/integrations/media-preprocessing',
    path: '/integrations/media-preprocessing',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthConversationsNewRoute = AuthConversationsNewRouteImport.update({
  id: '/conversations/new',
  path: '/conversations/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthContactsNewRoute = AuthContactsNewRouteImport.update({
  id: '/contacts/new',
  path: '/contacts/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthContactsContactIdRoute = AuthContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChatbotsFlowIdRoute = AuthChatbotsFlowIdRouteImport.update({
  id: '/chatbots/$flowId',
  path: '/chatbots/$flowId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCampaignsNewRoute = AuthCampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCampaignsCampaignIdRoute = AuthCampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsNewRoute = AuthAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsAgentIdRoute = AuthAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsWebhooksIndexRoute =
  AuthSettingsWebhooksIndexRouteImport.update({
    id: '/webhooks/',
    path: '/webhooks/',
    getParentRoute: () => AuthSettingsRoute,
  } as any)
const AuthSettingsOrganizationIndexRoute =
  AuthSettingsOrganizationIndexRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => AuthSettingsRoute,
  } as any)
const AuthSettingsMembersIndexRoute =
  AuthSettingsMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthSettingsRoute,
  } as any)
const AuthSettingsApiKeysIndexRoute =
  AuthSettingsApiKeysIndexRouteImport.update({
    id: '/api-keys/',
    path: '/api-keys/',
    getParentRoute: () => AuthSettingsRoute,
  } as any)
const AuthIntegrationsWhatsappIndexRoute =
  AuthIntegrationsWhatsappIndexRouteImport.update({
    id: '/integrations/whatsapp/',
    path: '/integrations/whatsapp/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsInstagramIndexRoute =
  AuthIntegrationsInstagramIndexRouteImport.update({
    id: '/integrations/instagram/',
    path: '/integrations/instagram/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTemplatesTemplateIdEditRoute =
  AuthTemplatesTemplateIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthTemplatesTemplateIdRoute,
  } as any)
const AuthSettingsWebhooksNewRoute = AuthSettingsWebhooksNewRouteImport.update({
  id: '/webhooks/new',
  path: '/webhooks/new',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsWebhooksWebhookIdRoute =
  AuthSettingsWebhooksWebhookIdRouteImport.update({
    id: '/webhooks/$webhookId',
    path: '/webhooks/$webhookId',
    getParentRoute: () => AuthSettingsRoute,
  } as any)
const AuthSettingsOrganizationNewRoute =
  AuthSettingsOrganizationNewRouteImport.update({
    id: '/organization/new',
    path: '/organization/new',
    getParentRoute: () => AuthSettingsRoute,
  } as any)
const AuthSettingsMembersNewRoute = AuthSettingsMembersNewRouteImport.update({
  id: '/members/new',
  path: '/members/new',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsMembersMemberIdRoute =
  AuthSettingsMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => AuthSettingsRoute,
  } as any)
const AuthSettingsApiKeysNewRoute = AuthSettingsApiKeysNewRouteImport.update({
  id: '/api-keys/new',
  path: '/api-keys/new',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsApiKeysApiKeyIdRoute =
  AuthSettingsApiKeysApiKeyIdRouteImport.update({
    id: '/api-keys/$apiKeyId',
    path: '/api-keys/$apiKeyId',
    getParentRoute: () => AuthSettingsRoute,
  } as any)
const AuthIntegrationsWhatsappNewRoute =
  AuthIntegrationsWhatsappNewRouteImport.update({
    id: '/integrations/whatsapp/new',
    path: '/integrations/whatsapp/new',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsInstagramNewRoute =
  AuthIntegrationsInstagramNewRouteImport.update({
    id: '/integrations/instagram/new',
    path: '/integrations/instagram/new',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthCampaignsCampaignIdReviewRoute =
  AuthCampaignsCampaignIdReviewRouteImport.update({
    id: '/campaigns/$campaignId_/review',
    path: '/campaigns/$campaignId/review',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthCampaignsCampaignIdEditRoute =
  AuthCampaignsCampaignIdEditRouteImport.update({
    id: '/campaigns/$campaignId_/edit',
    path: '/campaigns/$campaignId/edit',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsWhatsappOnboardingIndexRoute =
  AuthIntegrationsWhatsappOnboardingIndexRouteImport.update({
    id: '/integrations/whatsapp/onboarding/',
    path: '/integrations/whatsapp/onboarding/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsWhatsappOrgAddressIdIndexRoute =
  AuthIntegrationsWhatsappOrgAddressIdIndexRouteImport.update({
    id: '/integrations/whatsapp/$orgAddressId/',
    path: '/integrations/whatsapp/$orgAddressId/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsInstagramOnboardingIndexRoute =
  AuthIntegrationsInstagramOnboardingIndexRouteImport.update({
    id: '/integrations/instagram/onboarding/',
    path: '/integrations/instagram/onboarding/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsInstagramOrgAddressIdIndexRoute =
  AuthIntegrationsInstagramOrgAddressIdIndexRouteImport.update({
    id: '/integrations/instagram/$orgAddressId/',
    path: '/integrations/instagram/$orgAddressId/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsWhatsappOnboardingNewRoute =
  AuthIntegrationsWhatsappOnboardingNewRouteImport.update({
    id: '/integrations/whatsapp/onboarding/new',
    path: '/integrations/whatsapp/onboarding/new',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsWhatsappOnboardingTokenIdRoute =
  AuthIntegrationsWhatsappOnboardingTokenIdRouteImport.update({
    id: '/integrations/whatsapp/onboarding/$tokenId',
    path: '/integrations/whatsapp/onboarding/$tokenId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsWhatsappOrgAddressIdProfileRoute =
  AuthIntegrationsWhatsappOrgAddressIdProfileRouteImport.update({
    id: '/integrations/whatsapp/$orgAddressId/profile',
    path: '/integrations/whatsapp/$orgAddressId/profile',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsInstagramOnboardingNewRoute =
  AuthIntegrationsInstagramOnboardingNewRouteImport.update({
    id: '/integrations/instagram/onboarding/new',
    path: '/integrations/instagram/onboarding/new',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsInstagramOnboardingTokenIdRoute =
  AuthIntegrationsInstagramOnboardingTokenIdRouteImport.update({
    id: '/integrations/instagram/onboarding/$tokenId',
    path: '/integrations/instagram/onboarding/$tokenId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRoute =
  AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRouteImport.update({
    id: '/integrations/whatsapp/$orgAddressId/templates/',
    path: '/integrations/whatsapp/$orgAddressId/templates/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRoute =
  AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRouteImport.update({
    id: '/integrations/whatsapp/$orgAddressId/templates/new',
    path: '/integrations/whatsapp/$orgAddressId/templates/new',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRoute =
  AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRouteImport.update({
    id: '/integrations/whatsapp/$orgAddressId/templates/$templateId',
    path: '/integrations/whatsapp/$orgAddressId/templates/$templateId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-deletion': typeof DataDeletionRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/quick-replies': typeof AuthQuickRepliesRoute
  '/settings': typeof AuthSettingsRouteWithChildren
  '/stats': typeof AuthStatsRouteWithChildren
  '/whatsapp-manager': typeof AuthWhatsappManagerRoute
  '/login/email': typeof LoginEmailRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/instagram': typeof OauthInstagramRoute
  '/platform/$organizationId': typeof PlatformOrganizationIdRouteWithChildren
  '/platform/': typeof PlatformIndexRoute
  '/agents/$agentId': typeof AuthAgentsAgentIdRoute
  '/agents/new': typeof AuthAgentsNewRoute
  '/campaigns/$campaignId': typeof AuthCampaignsCampaignIdRoute
  '/campaigns/new': typeof AuthCampaignsNewRoute
  '/chatbots/$flowId': typeof AuthChatbotsFlowIdRoute
  '/contacts/$contactId': typeof AuthContactsContactIdRoute
  '/contacts/new': typeof AuthContactsNewRoute
  '/conversations/new': typeof AuthConversationsNewRoute
  '/integrations/media-preprocessing': typeof AuthIntegrationsMediaPreprocessingRoute
  '/settings/routing-queues': typeof AuthSettingsRoutingQueuesRoute
  '/stats/quotas': typeof AuthStatsQuotasRoute
  '/stats/usage': typeof AuthStatsUsageRoute
  '/templates/$templateId': typeof AuthTemplatesTemplateIdRouteWithChildren
  '/templates/new': typeof AuthTemplatesNewRoute
  '/onboard/instagram/$token': typeof OnboardInstagramTokenRoute
  '/onboard/instagram/callback': typeof OnboardInstagramCallbackRoute
  '/onboard/whatsapp/$token': typeof OnboardWhatsappTokenRoute
  '/platform/$organizationId/reports': typeof PlatformOrganizationIdReportsRoute
  '/agents': typeof AuthAgentsIndexRoute
  '/campaigns': typeof AuthCampaignsIndexRoute
  '/chatbots': typeof AuthChatbotsIndexRoute
  '/contacts': typeof AuthContactsIndexRoute
  '/conversations': typeof AuthConversationsIndexRoute
  '/integrations': typeof AuthIntegrationsIndexRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/stats/': typeof AuthStatsIndexRoute
  '/team-members': typeof AuthTeamMembersIndexRoute
  '/templates': typeof AuthTemplatesIndexRoute
  '/platform/$organizationId/': typeof PlatformOrganizationIdIndexRoute
  '/campaigns/$campaignId/edit': typeof AuthCampaignsCampaignIdEditRoute
  '/campaigns/$campaignId/review': typeof AuthCampaignsCampaignIdReviewRoute
  '/integrations/instagram/new': typeof AuthIntegrationsInstagramNewRoute
  '/integrations/whatsapp/new': typeof AuthIntegrationsWhatsappNewRoute
  '/settings/api-keys/$apiKeyId': typeof AuthSettingsApiKeysApiKeyIdRoute
  '/settings/api-keys/new': typeof AuthSettingsApiKeysNewRoute
  '/settings/members/$memberId': typeof AuthSettingsMembersMemberIdRoute
  '/settings/members/new': typeof AuthSettingsMembersNewRoute
  '/settings/organization/new': typeof AuthSettingsOrganizationNewRoute
  '/settings/webhooks/$webhookId': typeof AuthSettingsWebhooksWebhookIdRoute
  '/settings/webhooks/new': typeof AuthSettingsWebhooksNewRoute
  '/templates/$templateId/edit': typeof AuthTemplatesTemplateIdEditRoute
  '/integrations/instagram': typeof AuthIntegrationsInstagramIndexRoute
  '/integrations/whatsapp': typeof AuthIntegrationsWhatsappIndexRoute
  '/settings/api-keys': typeof AuthSettingsApiKeysIndexRoute
  '/settings/members': typeof AuthSettingsMembersIndexRoute
  '/settings/organization': typeof AuthSettingsOrganizationIndexRoute
  '/settings/webhooks': typeof AuthSettingsWebhooksIndexRoute
  '/integrations/instagram/onboarding/$tokenId': typeof AuthIntegrationsInstagramOnboardingTokenIdRoute
  '/integrations/instagram/onboarding/new': typeof AuthIntegrationsInstagramOnboardingNewRoute
  '/integrations/whatsapp/$orgAddressId/profile': typeof AuthIntegrationsWhatsappOrgAddressIdProfileRoute
  '/integrations/whatsapp/onboarding/$tokenId': typeof AuthIntegrationsWhatsappOnboardingTokenIdRoute
  '/integrations/whatsapp/onboarding/new': typeof AuthIntegrationsWhatsappOnboardingNewRoute
  '/integrations/instagram/$orgAddressId': typeof AuthIntegrationsInstagramOrgAddressIdIndexRoute
  '/integrations/instagram/onboarding': typeof AuthIntegrationsInstagramOnboardingIndexRoute
  '/integrations/whatsapp/$orgAddressId': typeof AuthIntegrationsWhatsappOrgAddressIdIndexRoute
  '/integrations/whatsapp/onboarding': typeof AuthIntegrationsWhatsappOnboardingIndexRoute
  '/integrations/whatsapp/$orgAddressId/templates/$templateId': typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRoute
  '/integrations/whatsapp/$orgAddressId/templates/new': typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRoute
  '/integrations/whatsapp/$orgAddressId/templates': typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-deletion': typeof DataDeletionRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/quick-replies': typeof AuthQuickRepliesRoute
  '/whatsapp-manager': typeof AuthWhatsappManagerRoute
  '/login/email': typeof LoginEmailRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/instagram': typeof OauthInstagramRoute
  '/platform': typeof PlatformIndexRoute
  '/agents/$agentId': typeof AuthAgentsAgentIdRoute
  '/agents/new': typeof AuthAgentsNewRoute
  '/campaigns/$campaignId': typeof AuthCampaignsCampaignIdRoute
  '/campaigns/new': typeof AuthCampaignsNewRoute
  '/chatbots/$flowId': typeof AuthChatbotsFlowIdRoute
  '/contacts/$contactId': typeof AuthContactsContactIdRoute
  '/contacts/new': typeof AuthContactsNewRoute
  '/conversations/new': typeof AuthConversationsNewRoute
  '/integrations/media-preprocessing': typeof AuthIntegrationsMediaPreprocessingRoute
  '/settings/routing-queues': typeof AuthSettingsRoutingQueuesRoute
  '/stats/quotas': typeof AuthStatsQuotasRoute
  '/stats/usage': typeof AuthStatsUsageRoute
  '/templates/$templateId': typeof AuthTemplatesTemplateIdRouteWithChildren
  '/templates/new': typeof AuthTemplatesNewRoute
  '/onboard/instagram/$token': typeof OnboardInstagramTokenRoute
  '/onboard/instagram/callback': typeof OnboardInstagramCallbackRoute
  '/onboard/whatsapp/$token': typeof OnboardWhatsappTokenRoute
  '/platform/$organizationId/reports': typeof PlatformOrganizationIdReportsRoute
  '/agents': typeof AuthAgentsIndexRoute
  '/campaigns': typeof AuthCampaignsIndexRoute
  '/chatbots': typeof AuthChatbotsIndexRoute
  '/contacts': typeof AuthContactsIndexRoute
  '/conversations': typeof AuthConversationsIndexRoute
  '/integrations': typeof AuthIntegrationsIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/stats': typeof AuthStatsIndexRoute
  '/team-members': typeof AuthTeamMembersIndexRoute
  '/templates': typeof AuthTemplatesIndexRoute
  '/platform/$organizationId': typeof PlatformOrganizationIdIndexRoute
  '/campaigns/$campaignId/edit': typeof AuthCampaignsCampaignIdEditRoute
  '/campaigns/$campaignId/review': typeof AuthCampaignsCampaignIdReviewRoute
  '/integrations/instagram/new': typeof AuthIntegrationsInstagramNewRoute
  '/integrations/whatsapp/new': typeof AuthIntegrationsWhatsappNewRoute
  '/settings/api-keys/$apiKeyId': typeof AuthSettingsApiKeysApiKeyIdRoute
  '/settings/api-keys/new': typeof AuthSettingsApiKeysNewRoute
  '/settings/members/$memberId': typeof AuthSettingsMembersMemberIdRoute
  '/settings/members/new': typeof AuthSettingsMembersNewRoute
  '/settings/organization/new': typeof AuthSettingsOrganizationNewRoute
  '/settings/webhooks/$webhookId': typeof AuthSettingsWebhooksWebhookIdRoute
  '/settings/webhooks/new': typeof AuthSettingsWebhooksNewRoute
  '/templates/$templateId/edit': typeof AuthTemplatesTemplateIdEditRoute
  '/integrations/instagram': typeof AuthIntegrationsInstagramIndexRoute
  '/integrations/whatsapp': typeof AuthIntegrationsWhatsappIndexRoute
  '/settings/api-keys': typeof AuthSettingsApiKeysIndexRoute
  '/settings/members': typeof AuthSettingsMembersIndexRoute
  '/settings/organization': typeof AuthSettingsOrganizationIndexRoute
  '/settings/webhooks': typeof AuthSettingsWebhooksIndexRoute
  '/integrations/instagram/onboarding/$tokenId': typeof AuthIntegrationsInstagramOnboardingTokenIdRoute
  '/integrations/instagram/onboarding/new': typeof AuthIntegrationsInstagramOnboardingNewRoute
  '/integrations/whatsapp/$orgAddressId/profile': typeof AuthIntegrationsWhatsappOrgAddressIdProfileRoute
  '/integrations/whatsapp/onboarding/$tokenId': typeof AuthIntegrationsWhatsappOnboardingTokenIdRoute
  '/integrations/whatsapp/onboarding/new': typeof AuthIntegrationsWhatsappOnboardingNewRoute
  '/integrations/instagram/$orgAddressId': typeof AuthIntegrationsInstagramOrgAddressIdIndexRoute
  '/integrations/instagram/onboarding': typeof AuthIntegrationsInstagramOnboardingIndexRoute
  '/integrations/whatsapp/$orgAddressId': typeof AuthIntegrationsWhatsappOrgAddressIdIndexRoute
  '/integrations/whatsapp/onboarding': typeof AuthIntegrationsWhatsappOnboardingIndexRoute
  '/integrations/whatsapp/$orgAddressId/templates/$templateId': typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRoute
  '/integrations/whatsapp/$orgAddressId/templates/new': typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRoute
  '/integrations/whatsapp/$orgAddressId/templates': typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/data-deletion': typeof DataDeletionRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/quick-replies': typeof AuthQuickRepliesRoute
  '/_auth/settings': typeof AuthSettingsRouteWithChildren
  '/_auth/stats': typeof AuthStatsRouteWithChildren
  '/_auth/whatsapp-manager': typeof AuthWhatsappManagerRoute
  '/login_/email': typeof LoginEmailRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/instagram': typeof OauthInstagramRoute
  '/platform/$organizationId': typeof PlatformOrganizationIdRouteWithChildren
  '/platform/': typeof PlatformIndexRoute
  '/_auth/agents/$agentId': typeof AuthAgentsAgentIdRoute
  '/_auth/agents/new': typeof AuthAgentsNewRoute
  '/_auth/campaigns/$campaignId': typeof AuthCampaignsCampaignIdRoute
  '/_auth/campaigns/new': typeof AuthCampaignsNewRoute
  '/_auth/chatbots/$flowId': typeof AuthChatbotsFlowIdRoute
  '/_auth/contacts/$contactId': typeof AuthContactsContactIdRoute
  '/_auth/contacts/new': typeof AuthContactsNewRoute
  '/_auth/conversations/new': typeof AuthConversationsNewRoute
  '/_auth/integrations/media-preprocessing': typeof AuthIntegrationsMediaPreprocessingRoute
  '/_auth/settings/routing-queues': typeof AuthSettingsRoutingQueuesRoute
  '/_auth/stats/quotas': typeof AuthStatsQuotasRoute
  '/_auth/stats/usage': typeof AuthStatsUsageRoute
  '/_auth/templates/$templateId': typeof AuthTemplatesTemplateIdRouteWithChildren
  '/_auth/templates/new': typeof AuthTemplatesNewRoute
  '/onboard/instagram/$token': typeof OnboardInstagramTokenRoute
  '/onboard/instagram/callback': typeof OnboardInstagramCallbackRoute
  '/onboard/whatsapp/$token': typeof OnboardWhatsappTokenRoute
  '/platform/$organizationId/reports': typeof PlatformOrganizationIdReportsRoute
  '/_auth/agents/': typeof AuthAgentsIndexRoute
  '/_auth/campaigns/': typeof AuthCampaignsIndexRoute
  '/_auth/chatbots/': typeof AuthChatbotsIndexRoute
  '/_auth/contacts/': typeof AuthContactsIndexRoute
  '/_auth/conversations/': typeof AuthConversationsIndexRoute
  '/_auth/integrations/': typeof AuthIntegrationsIndexRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/stats/': typeof AuthStatsIndexRoute
  '/_auth/team-members/': typeof AuthTeamMembersIndexRoute
  '/_auth/templates/': typeof AuthTemplatesIndexRoute
  '/platform/$organizationId/': typeof PlatformOrganizationIdIndexRoute
  '/_auth/campaigns/$campaignId_/edit': typeof AuthCampaignsCampaignIdEditRoute
  '/_auth/campaigns/$campaignId_/review': typeof AuthCampaignsCampaignIdReviewRoute
  '/_auth/integrations/instagram/new': typeof AuthIntegrationsInstagramNewRoute
  '/_auth/integrations/whatsapp/new': typeof AuthIntegrationsWhatsappNewRoute
  '/_auth/settings/api-keys/$apiKeyId': typeof AuthSettingsApiKeysApiKeyIdRoute
  '/_auth/settings/api-keys/new': typeof AuthSettingsApiKeysNewRoute
  '/_auth/settings/members/$memberId': typeof AuthSettingsMembersMemberIdRoute
  '/_auth/settings/members/new': typeof AuthSettingsMembersNewRoute
  '/_auth/settings/organization/new': typeof AuthSettingsOrganizationNewRoute
  '/_auth/settings/webhooks/$webhookId': typeof AuthSettingsWebhooksWebhookIdRoute
  '/_auth/settings/webhooks/new': typeof AuthSettingsWebhooksNewRoute
  '/_auth/templates/$templateId/edit': typeof AuthTemplatesTemplateIdEditRoute
  '/_auth/integrations/instagram/': typeof AuthIntegrationsInstagramIndexRoute
  '/_auth/integrations/whatsapp/': typeof AuthIntegrationsWhatsappIndexRoute
  '/_auth/settings/api-keys/': typeof AuthSettingsApiKeysIndexRoute
  '/_auth/settings/members/': typeof AuthSettingsMembersIndexRoute
  '/_auth/settings/organization/': typeof AuthSettingsOrganizationIndexRoute
  '/_auth/settings/webhooks/': typeof AuthSettingsWebhooksIndexRoute
  '/_auth/integrations/instagram/onboarding/$tokenId': typeof AuthIntegrationsInstagramOnboardingTokenIdRoute
  '/_auth/integrations/instagram/onboarding/new': typeof AuthIntegrationsInstagramOnboardingNewRoute
  '/_auth/integrations/whatsapp/$orgAddressId/profile': typeof AuthIntegrationsWhatsappOrgAddressIdProfileRoute
  '/_auth/integrations/whatsapp/onboarding/$tokenId': typeof AuthIntegrationsWhatsappOnboardingTokenIdRoute
  '/_auth/integrations/whatsapp/onboarding/new': typeof AuthIntegrationsWhatsappOnboardingNewRoute
  '/_auth/integrations/instagram/$orgAddressId/': typeof AuthIntegrationsInstagramOrgAddressIdIndexRoute
  '/_auth/integrations/instagram/onboarding/': typeof AuthIntegrationsInstagramOnboardingIndexRoute
  '/_auth/integrations/whatsapp/$orgAddressId/': typeof AuthIntegrationsWhatsappOrgAddressIdIndexRoute
  '/_auth/integrations/whatsapp/onboarding/': typeof AuthIntegrationsWhatsappOnboardingIndexRoute
  '/_auth/integrations/whatsapp/$orgAddressId/templates/$templateId': typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRoute
  '/_auth/integrations/whatsapp/$orgAddressId/templates/new': typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRoute
  '/_auth/integrations/whatsapp/$orgAddressId/templates/': typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-deletion'
    | '/login'
    | '/platform'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/quick-replies'
    | '/settings'
    | '/stats'
    | '/whatsapp-manager'
    | '/login/email'
    | '/oauth/callback'
    | '/oauth/instagram'
    | '/platform/$organizationId'
    | '/platform/'
    | '/agents/$agentId'
    | '/agents/new'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/chatbots/$flowId'
    | '/contacts/$contactId'
    | '/contacts/new'
    | '/conversations/new'
    | '/integrations/media-preprocessing'
    | '/settings/routing-queues'
    | '/stats/quotas'
    | '/stats/usage'
    | '/templates/$templateId'
    | '/templates/new'
    | '/onboard/instagram/$token'
    | '/onboard/instagram/callback'
    | '/onboard/whatsapp/$token'
    | '/platform/$organizationId/reports'
    | '/agents'
    | '/campaigns'
    | '/chatbots'
    | '/contacts'
    | '/conversations'
    | '/integrations'
    | '/settings/'
    | '/stats/'
    | '/team-members'
    | '/templates'
    | '/platform/$organizationId/'
    | '/campaigns/$campaignId/edit'
    | '/campaigns/$campaignId/review'
    | '/integrations/instagram/new'
    | '/integrations/whatsapp/new'
    | '/settings/api-keys/$apiKeyId'
    | '/settings/api-keys/new'
    | '/settings/members/$memberId'
    | '/settings/members/new'
    | '/settings/organization/new'
    | '/settings/webhooks/$webhookId'
    | '/settings/webhooks/new'
    | '/templates/$templateId/edit'
    | '/integrations/instagram'
    | '/integrations/whatsapp'
    | '/settings/api-keys'
    | '/settings/members'
    | '/settings/organization'
    | '/settings/webhooks'
    | '/integrations/instagram/onboarding/$tokenId'
    | '/integrations/instagram/onboarding/new'
    | '/integrations/whatsapp/$orgAddressId/profile'
    | '/integrations/whatsapp/onboarding/$tokenId'
    | '/integrations/whatsapp/onboarding/new'
    | '/integrations/instagram/$orgAddressId'
    | '/integrations/instagram/onboarding'
    | '/integrations/whatsapp/$orgAddressId'
    | '/integrations/whatsapp/onboarding'
    | '/integrations/whatsapp/$orgAddressId/templates/$templateId'
    | '/integrations/whatsapp/$orgAddressId/templates/new'
    | '/integrations/whatsapp/$orgAddressId/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-deletion'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/quick-replies'
    | '/whatsapp-manager'
    | '/login/email'
    | '/oauth/callback'
    | '/oauth/instagram'
    | '/platform'
    | '/agents/$agentId'
    | '/agents/new'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/chatbots/$flowId'
    | '/contacts/$contactId'
    | '/contacts/new'
    | '/conversations/new'
    | '/integrations/media-preprocessing'
    | '/settings/routing-queues'
    | '/stats/quotas'
    | '/stats/usage'
    | '/templates/$templateId'
    | '/templates/new'
    | '/onboard/instagram/$token'
    | '/onboard/instagram/callback'
    | '/onboard/whatsapp/$token'
    | '/platform/$organizationId/reports'
    | '/agents'
    | '/campaigns'
    | '/chatbots'
    | '/contacts'
    | '/conversations'
    | '/integrations'
    | '/settings'
    | '/stats'
    | '/team-members'
    | '/templates'
    | '/platform/$organizationId'
    | '/campaigns/$campaignId/edit'
    | '/campaigns/$campaignId/review'
    | '/integrations/instagram/new'
    | '/integrations/whatsapp/new'
    | '/settings/api-keys/$apiKeyId'
    | '/settings/api-keys/new'
    | '/settings/members/$memberId'
    | '/settings/members/new'
    | '/settings/organization/new'
    | '/settings/webhooks/$webhookId'
    | '/settings/webhooks/new'
    | '/templates/$templateId/edit'
    | '/integrations/instagram'
    | '/integrations/whatsapp'
    | '/settings/api-keys'
    | '/settings/members'
    | '/settings/organization'
    | '/settings/webhooks'
    | '/integrations/instagram/onboarding/$tokenId'
    | '/integrations/instagram/onboarding/new'
    | '/integrations/whatsapp/$orgAddressId/profile'
    | '/integrations/whatsapp/onboarding/$tokenId'
    | '/integrations/whatsapp/onboarding/new'
    | '/integrations/instagram/$orgAddressId'
    | '/integrations/instagram/onboarding'
    | '/integrations/whatsapp/$orgAddressId'
    | '/integrations/whatsapp/onboarding'
    | '/integrations/whatsapp/$orgAddressId/templates/$templateId'
    | '/integrations/whatsapp/$orgAddressId/templates/new'
    | '/integrations/whatsapp/$orgAddressId/templates'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/data-deletion'
    | '/login'
    | '/platform'
    | '/privacy'
    | '/terms'
    | '/_auth/dashboard'
    | '/_auth/quick-replies'
    | '/_auth/settings'
    | '/_auth/stats'
    | '/_auth/whatsapp-manager'
    | '/login_/email'
    | '/oauth/callback'
    | '/oauth/instagram'
    | '/platform/$organizationId'
    | '/platform/'
    | '/_auth/agents/$agentId'
    | '/_auth/agents/new'
    | '/_auth/campaigns/$campaignId'
    | '/_auth/campaigns/new'
    | '/_auth/chatbots/$flowId'
    | '/_auth/contacts/$contactId'
    | '/_auth/contacts/new'
    | '/_auth/conversations/new'
    | '/_auth/integrations/media-preprocessing'
    | '/_auth/settings/routing-queues'
    | '/_auth/stats/quotas'
    | '/_auth/stats/usage'
    | '/_auth/templates/$templateId'
    | '/_auth/templates/new'
    | '/onboard/instagram/$token'
    | '/onboard/instagram/callback'
    | '/onboard/whatsapp/$token'
    | '/platform/$organizationId/reports'
    | '/_auth/agents/'
    | '/_auth/campaigns/'
    | '/_auth/chatbots/'
    | '/_auth/contacts/'
    | '/_auth/conversations/'
    | '/_auth/integrations/'
    | '/_auth/settings/'
    | '/_auth/stats/'
    | '/_auth/team-members/'
    | '/_auth/templates/'
    | '/platform/$organizationId/'
    | '/_auth/campaigns/$campaignId_/edit'
    | '/_auth/campaigns/$campaignId_/review'
    | '/_auth/integrations/instagram/new'
    | '/_auth/integrations/whatsapp/new'
    | '/_auth/settings/api-keys/$apiKeyId'
    | '/_auth/settings/api-keys/new'
    | '/_auth/settings/members/$memberId'
    | '/_auth/settings/members/new'
    | '/_auth/settings/organization/new'
    | '/_auth/settings/webhooks/$webhookId'
    | '/_auth/settings/webhooks/new'
    | '/_auth/templates/$templateId/edit'
    | '/_auth/integrations/instagram/'
    | '/_auth/integrations/whatsapp/'
    | '/_auth/settings/api-keys/'
    | '/_auth/settings/members/'
    | '/_auth/settings/organization/'
    | '/_auth/settings/webhooks/'
    | '/_auth/integrations/instagram/onboarding/$tokenId'
    | '/_auth/integrations/instagram/onboarding/new'
    | '/_auth/integrations/whatsapp/$orgAddressId/profile'
    | '/_auth/integrations/whatsapp/onboarding/$tokenId'
    | '/_auth/integrations/whatsapp/onboarding/new'
    | '/_auth/integrations/instagram/$orgAddressId/'
    | '/_auth/integrations/instagram/onboarding/'
    | '/_auth/integrations/whatsapp/$orgAddressId/'
    | '/_auth/integrations/whatsapp/onboarding/'
    | '/_auth/integrations/whatsapp/$orgAddressId/templates/$templateId'
    | '/_auth/integrations/whatsapp/$orgAddressId/templates/new'
    | '/_auth/integrations/whatsapp/$orgAddressId/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DataDeletionRoute: typeof DataDeletionRoute
  LoginRoute: typeof LoginRoute
  PlatformRoute: typeof PlatformRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  LoginEmailRoute: typeof LoginEmailRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  OauthInstagramRoute: typeof OauthInstagramRoute
  OnboardInstagramTokenRoute: typeof OnboardInstagramTokenRoute
  OnboardInstagramCallbackRoute: typeof OnboardInstagramCallbackRoute
  OnboardWhatsappTokenRoute: typeof OnboardWhatsappTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/$organizationId': {
      id: '/platform/$organizationId'
      path: '/$organizationId'
      fullPath: '/platform/$organizationId'
      preLoaderRoute: typeof PlatformOrganizationIdRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/oauth/instagram': {
      id: '/oauth/instagram'
      path: '/oauth/instagram'
      fullPath: '/oauth/instagram'
      preLoaderRoute: typeof OauthInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/email': {
      id: '/login_/email'
      path: '/login/email'
      fullPath: '/login/email'
      preLoaderRoute: typeof LoginEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/whatsapp-manager': {
      id: '/_auth/whatsapp-manager'
      path: '/whatsapp-manager'
      fullPath: '/whatsapp-manager'
      preLoaderRoute: typeof AuthWhatsappManagerRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/stats': {
      id: '/_auth/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthStatsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/quick-replies': {
      id: '/_auth/quick-replies'
      path: '/quick-replies'
      fullPath: '/quick-replies'
      preLoaderRoute: typeof AuthQuickRepliesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/platform/$organizationId/': {
      id: '/platform/$organizationId/'
      path: '/'
      fullPath: '/platform/$organizationId/'
      preLoaderRoute: typeof PlatformOrganizationIdIndexRouteImport
      parentRoute: typeof PlatformOrganizationIdRoute
    }
    '/_auth/templates/': {
      id: '/_auth/templates/'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthTemplatesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/team-members/': {
      id: '/_auth/team-members/'
      path: '/team-members'
      fullPath: '/team-members'
      preLoaderRoute: typeof AuthTeamMembersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/stats/': {
      id: '/_auth/stats/'
      path: '/'
      fullPath: '/stats/'
      preLoaderRoute: typeof AuthStatsIndexRouteImport
      parentRoute: typeof AuthStatsRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/integrations/': {
      id: '/_auth/integrations/'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthIntegrationsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/conversations/': {
      id: '/_auth/conversations/'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthConversationsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/contacts/': {
      id: '/_auth/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthContactsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/chatbots/': {
      id: '/_auth/chatbots/'
      path: '/chatbots'
      fullPath: '/chatbots'
      preLoaderRoute: typeof AuthChatbotsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/campaigns/': {
      id: '/_auth/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthCampaignsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents/': {
      id: '/_auth/agents/'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthAgentsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/platform/$organizationId/reports': {
      id: '/platform/$organizationId/reports'
      path: '/reports'
      fullPath: '/platform/$organizationId/reports'
      preLoaderRoute: typeof PlatformOrganizationIdReportsRouteImport
      parentRoute: typeof PlatformOrganizationIdRoute
    }
    '/onboard/whatsapp/$token': {
      id: '/onboard/whatsapp/$token'
      path: '/onboard/whatsapp/$token'
      fullPath: '/onboard/whatsapp/$token'
      preLoaderRoute: typeof OnboardWhatsappTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard/instagram/callback': {
      id: '/onboard/instagram/callback'
      path: '/onboard/instagram/callback'
      fullPath: '/onboard/instagram/callback'
      preLoaderRoute: typeof OnboardInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard/instagram/$token': {
      id: '/onboard/instagram/$token'
      path: '/onboard/instagram/$token'
      fullPath: '/onboard/instagram/$token'
      preLoaderRoute: typeof OnboardInstagramTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/templates/new': {
      id: '/_auth/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof AuthTemplatesNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/templates/$templateId': {
      id: '/_auth/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof AuthTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/stats/usage': {
      id: '/_auth/stats/usage'
      path: '/usage'
      fullPath: '/stats/usage'
      preLoaderRoute: typeof AuthStatsUsageRouteImport
      parentRoute: typeof AuthStatsRoute
    }
    '/_auth/stats/quotas': {
      id: '/_auth/stats/quotas'
      path: '/quotas'
      fullPath: '/stats/quotas'
      preLoaderRoute: typeof AuthStatsQuotasRouteImport
      parentRoute: typeof AuthStatsRoute
    }
    '/_auth/settings/routing-queues': {
      id: '/_auth/settings/routing-queues'
      path: '/routing-queues'
      fullPath: '/settings/routing-queues'
      preLoaderRoute: typeof AuthSettingsRoutingQueuesRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/integrations/media-preprocessing': {
      id: '/_auth/integrations/media-preprocessing'
      path: '/integrations/media-preprocessing'
      fullPath: '/integrations/media-preprocessing'
      preLoaderRoute: typeof AuthIntegrationsMediaPreprocessingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/conversations/new': {
      id: '/_auth/conversations/new'
      path: '/conversations/new'
      fullPath: '/conversations/new'
      preLoaderRoute: typeof AuthConversationsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/contacts/new': {
      id: '/_auth/contacts/new'
      path: '/contacts/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof AuthContactsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/contacts/$contactId': {
      id: '/_auth/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof AuthContactsContactIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/chatbots/$flowId': {
      id: '/_auth/chatbots/$flowId'
      path: '/chatbots/$flowId'
      fullPath: '/chatbots/$flowId'
      preLoaderRoute: typeof AuthChatbotsFlowIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/campaigns/new': {
      id: '/_auth/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AuthCampaignsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/campaigns/$campaignId': {
      id: '/_auth/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof AuthCampaignsCampaignIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents/new': {
      id: '/_auth/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AuthAgentsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents/$agentId': {
      id: '/_auth/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthAgentsAgentIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/webhooks/': {
      id: '/_auth/settings/webhooks/'
      path: '/webhooks'
      fullPath: '/settings/webhooks'
      preLoaderRoute: typeof AuthSettingsWebhooksIndexRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/organization/': {
      id: '/_auth/settings/organization/'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthSettingsOrganizationIndexRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/members/': {
      id: '/_auth/settings/members/'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AuthSettingsMembersIndexRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/api-keys/': {
      id: '/_auth/settings/api-keys/'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthSettingsApiKeysIndexRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/integrations/whatsapp/': {
      id: '/_auth/integrations/whatsapp/'
      path: '/integrations/whatsapp'
      fullPath: '/integrations/whatsapp'
      preLoaderRoute: typeof AuthIntegrationsWhatsappIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/instagram/': {
      id: '/_auth/integrations/instagram/'
      path: '/integrations/instagram'
      fullPath: '/integrations/instagram'
      preLoaderRoute: typeof AuthIntegrationsInstagramIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/templates/$templateId/edit': {
      id: '/_auth/templates/$templateId/edit'
      path: '/edit'
      fullPath: '/templates/$templateId/edit'
      preLoaderRoute: typeof AuthTemplatesTemplateIdEditRouteImport
      parentRoute: typeof AuthTemplatesTemplateIdRoute
    }
    '/_auth/settings/webhooks/new': {
      id: '/_auth/settings/webhooks/new'
      path: '/webhooks/new'
      fullPath: '/settings/webhooks/new'
      preLoaderRoute: typeof AuthSettingsWebhooksNewRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/webhooks/$webhookId': {
      id: '/_auth/settings/webhooks/$webhookId'
      path: '/webhooks/$webhookId'
      fullPath: '/settings/webhooks/$webhookId'
      preLoaderRoute: typeof AuthSettingsWebhooksWebhookIdRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/organization/new': {
      id: '/_auth/settings/organization/new'
      path: '/organization/new'
      fullPath: '/settings/organization/new'
      preLoaderRoute: typeof AuthSettingsOrganizationNewRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/members/new': {
      id: '/_auth/settings/members/new'
      path: '/members/new'
      fullPath: '/settings/members/new'
      preLoaderRoute: typeof AuthSettingsMembersNewRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/members/$memberId': {
      id: '/_auth/settings/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/settings/members/$memberId'
      preLoaderRoute: typeof AuthSettingsMembersMemberIdRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/api-keys/new': {
      id: '/_auth/settings/api-keys/new'
      path: '/api-keys/new'
      fullPath: '/settings/api-keys/new'
      preLoaderRoute: typeof AuthSettingsApiKeysNewRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/api-keys/$apiKeyId': {
      id: '/_auth/settings/api-keys/$apiKeyId'
      path: '/api-keys/$apiKeyId'
      fullPath: '/settings/api-keys/$apiKeyId'
      preLoaderRoute: typeof AuthSettingsApiKeysApiKeyIdRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/integrations/whatsapp/new': {
      id: '/_auth/integrations/whatsapp/new'
      path: '/integrations/whatsapp/new'
      fullPath: '/integrations/whatsapp/new'
      preLoaderRoute: typeof AuthIntegrationsWhatsappNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/instagram/new': {
      id: '/_auth/integrations/instagram/new'
      path: '/integrations/instagram/new'
      fullPath: '/integrations/instagram/new'
      preLoaderRoute: typeof AuthIntegrationsInstagramNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/campaigns/$campaignId_/review': {
      id: '/_auth/campaigns/$campaignId_/review'
      path: '/campaigns/$campaignId/review'
      fullPath: '/campaigns/$campaignId/review'
      preLoaderRoute: typeof AuthCampaignsCampaignIdReviewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/campaigns/$campaignId_/edit': {
      id: '/_auth/campaigns/$campaignId_/edit'
      path: '/campaigns/$campaignId/edit'
      fullPath: '/campaigns/$campaignId/edit'
      preLoaderRoute: typeof AuthCampaignsCampaignIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/whatsapp/onboarding/': {
      id: '/_auth/integrations/whatsapp/onboarding/'
      path: '/integrations/whatsapp/onboarding'
      fullPath: '/integrations/whatsapp/onboarding'
      preLoaderRoute: typeof AuthIntegrationsWhatsappOnboardingIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/whatsapp/$orgAddressId/': {
      id: '/_auth/integrations/whatsapp/$orgAddressId/'
      path: '/integrations/whatsapp/$orgAddressId'
      fullPath: '/integrations/whatsapp/$orgAddressId'
      preLoaderRoute: typeof AuthIntegrationsWhatsappOrgAddressIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/instagram/onboarding/': {
      id: '/_auth/integrations/instagram/onboarding/'
      path: '/integrations/instagram/onboarding'
      fullPath: '/integrations/instagram/onboarding'
      preLoaderRoute: typeof AuthIntegrationsInstagramOnboardingIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/instagram/$orgAddressId/': {
      id: '/_auth/integrations/instagram/$orgAddressId/'
      path: '/integrations/instagram/$orgAddressId'
      fullPath: '/integrations/instagram/$orgAddressId'
      preLoaderRoute: typeof AuthIntegrationsInstagramOrgAddressIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/whatsapp/onboarding/new': {
      id: '/_auth/integrations/whatsapp/onboarding/new'
      path: '/integrations/whatsapp/onboarding/new'
      fullPath: '/integrations/whatsapp/onboarding/new'
      preLoaderRoute: typeof AuthIntegrationsWhatsappOnboardingNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/whatsapp/onboarding/$tokenId': {
      id: '/_auth/integrations/whatsapp/onboarding/$tokenId'
      path: '/integrations/whatsapp/onboarding/$tokenId'
      fullPath: '/integrations/whatsapp/onboarding/$tokenId'
      preLoaderRoute: typeof AuthIntegrationsWhatsappOnboardingTokenIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/whatsapp/$orgAddressId/profile': {
      id: '/_auth/integrations/whatsapp/$orgAddressId/profile'
      path: '/integrations/whatsapp/$orgAddressId/profile'
      fullPath: '/integrations/whatsapp/$orgAddressId/profile'
      preLoaderRoute: typeof AuthIntegrationsWhatsappOrgAddressIdProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/instagram/onboarding/new': {
      id: '/_auth/integrations/instagram/onboarding/new'
      path: '/integrations/instagram/onboarding/new'
      fullPath: '/integrations/instagram/onboarding/new'
      preLoaderRoute: typeof AuthIntegrationsInstagramOnboardingNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/instagram/onboarding/$tokenId': {
      id: '/_auth/integrations/instagram/onboarding/$tokenId'
      path: '/integrations/instagram/onboarding/$tokenId'
      fullPath: '/integrations/instagram/onboarding/$tokenId'
      preLoaderRoute: typeof AuthIntegrationsInstagramOnboardingTokenIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/whatsapp/$orgAddressId/templates/': {
      id: '/_auth/integrations/whatsapp/$orgAddressId/templates/'
      path: '/integrations/whatsapp/$orgAddressId/templates'
      fullPath: '/integrations/whatsapp/$orgAddressId/templates'
      preLoaderRoute: typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/whatsapp/$orgAddressId/templates/new': {
      id: '/_auth/integrations/whatsapp/$orgAddressId/templates/new'
      path: '/integrations/whatsapp/$orgAddressId/templates/new'
      fullPath: '/integrations/whatsapp/$orgAddressId/templates/new'
      preLoaderRoute: typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/whatsapp/$orgAddressId/templates/$templateId': {
      id: '/_auth/integrations/whatsapp/$orgAddressId/templates/$templateId'
      path: '/integrations/whatsapp/$orgAddressId/templates/$templateId'
      fullPath: '/integrations/whatsapp/$orgAddressId/templates/$templateId'
      preLoaderRoute: typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthSettingsRouteChildren {
  AuthSettingsRoutingQueuesRoute: typeof AuthSettingsRoutingQueuesRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
  AuthSettingsApiKeysApiKeyIdRoute: typeof AuthSettingsApiKeysApiKeyIdRoute
  AuthSettingsApiKeysNewRoute: typeof AuthSettingsApiKeysNewRoute
  AuthSettingsMembersMemberIdRoute: typeof AuthSettingsMembersMemberIdRoute
  AuthSettingsMembersNewRoute: typeof AuthSettingsMembersNewRoute
  AuthSettingsOrganizationNewRoute: typeof AuthSettingsOrganizationNewRoute
  AuthSettingsWebhooksWebhookIdRoute: typeof AuthSettingsWebhooksWebhookIdRoute
  AuthSettingsWebhooksNewRoute: typeof AuthSettingsWebhooksNewRoute
  AuthSettingsApiKeysIndexRoute: typeof AuthSettingsApiKeysIndexRoute
  AuthSettingsMembersIndexRoute: typeof AuthSettingsMembersIndexRoute
  AuthSettingsOrganizationIndexRoute: typeof AuthSettingsOrganizationIndexRoute
  AuthSettingsWebhooksIndexRoute: typeof AuthSettingsWebhooksIndexRoute
}

const AuthSettingsRouteChildren: AuthSettingsRouteChildren = {
  AuthSettingsRoutingQueuesRoute: AuthSettingsRoutingQueuesRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
  AuthSettingsApiKeysApiKeyIdRoute: AuthSettingsApiKeysApiKeyIdRoute,
  AuthSettingsApiKeysNewRoute: AuthSettingsApiKeysNewRoute,
  AuthSettingsMembersMemberIdRoute: AuthSettingsMembersMemberIdRoute,
  AuthSettingsMembersNewRoute: AuthSettingsMembersNewRoute,
  AuthSettingsOrganizationNewRoute: AuthSettingsOrganizationNewRoute,
  AuthSettingsWebhooksWebhookIdRoute: AuthSettingsWebhooksWebhookIdRoute,
  AuthSettingsWebhooksNewRoute: AuthSettingsWebhooksNewRoute,
  AuthSettingsApiKeysIndexRoute: AuthSettingsApiKeysIndexRoute,
  AuthSettingsMembersIndexRoute: AuthSettingsMembersIndexRoute,
  AuthSettingsOrganizationIndexRoute: AuthSettingsOrganizationIndexRoute,
  AuthSettingsWebhooksIndexRoute: AuthSettingsWebhooksIndexRoute,
}

const AuthSettingsRouteWithChildren = AuthSettingsRoute._addFileChildren(
  AuthSettingsRouteChildren,
)

interface AuthStatsRouteChildren {
  AuthStatsQuotasRoute: typeof AuthStatsQuotasRoute
  AuthStatsUsageRoute: typeof AuthStatsUsageRoute
  AuthStatsIndexRoute: typeof AuthStatsIndexRoute
}

const AuthStatsRouteChildren: AuthStatsRouteChildren = {
  AuthStatsQuotasRoute: AuthStatsQuotasRoute,
  AuthStatsUsageRoute: AuthStatsUsageRoute,
  AuthStatsIndexRoute: AuthStatsIndexRoute,
}

const AuthStatsRouteWithChildren = AuthStatsRoute._addFileChildren(
  AuthStatsRouteChildren,
)

interface AuthTemplatesTemplateIdRouteChildren {
  AuthTemplatesTemplateIdEditRoute: typeof AuthTemplatesTemplateIdEditRoute
}

const AuthTemplatesTemplateIdRouteChildren: AuthTemplatesTemplateIdRouteChildren =
  {
    AuthTemplatesTemplateIdEditRoute: AuthTemplatesTemplateIdEditRoute,
  }

const AuthTemplatesTemplateIdRouteWithChildren =
  AuthTemplatesTemplateIdRoute._addFileChildren(
    AuthTemplatesTemplateIdRouteChildren,
  )

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthQuickRepliesRoute: typeof AuthQuickRepliesRoute
  AuthSettingsRoute: typeof AuthSettingsRouteWithChildren
  AuthStatsRoute: typeof AuthStatsRouteWithChildren
  AuthWhatsappManagerRoute: typeof AuthWhatsappManagerRoute
  AuthAgentsAgentIdRoute: typeof AuthAgentsAgentIdRoute
  AuthAgentsNewRoute: typeof AuthAgentsNewRoute
  AuthCampaignsCampaignIdRoute: typeof AuthCampaignsCampaignIdRoute
  AuthCampaignsNewRoute: typeof AuthCampaignsNewRoute
  AuthChatbotsFlowIdRoute: typeof AuthChatbotsFlowIdRoute
  AuthContactsContactIdRoute: typeof AuthContactsContactIdRoute
  AuthContactsNewRoute: typeof AuthContactsNewRoute
  AuthConversationsNewRoute: typeof AuthConversationsNewRoute
  AuthIntegrationsMediaPreprocessingRoute: typeof AuthIntegrationsMediaPreprocessingRoute
  AuthTemplatesTemplateIdRoute: typeof AuthTemplatesTemplateIdRouteWithChildren
  AuthTemplatesNewRoute: typeof AuthTemplatesNewRoute
  AuthAgentsIndexRoute: typeof AuthAgentsIndexRoute
  AuthCampaignsIndexRoute: typeof AuthCampaignsIndexRoute
  AuthChatbotsIndexRoute: typeof AuthChatbotsIndexRoute
  AuthContactsIndexRoute: typeof AuthContactsIndexRoute
  AuthConversationsIndexRoute: typeof AuthConversationsIndexRoute
  AuthIntegrationsIndexRoute: typeof AuthIntegrationsIndexRoute
  AuthTeamMembersIndexRoute: typeof AuthTeamMembersIndexRoute
  AuthTemplatesIndexRoute: typeof AuthTemplatesIndexRoute
  AuthCampaignsCampaignIdEditRoute: typeof AuthCampaignsCampaignIdEditRoute
  AuthCampaignsCampaignIdReviewRoute: typeof AuthCampaignsCampaignIdReviewRoute
  AuthIntegrationsInstagramNewRoute: typeof AuthIntegrationsInstagramNewRoute
  AuthIntegrationsWhatsappNewRoute: typeof AuthIntegrationsWhatsappNewRoute
  AuthIntegrationsInstagramIndexRoute: typeof AuthIntegrationsInstagramIndexRoute
  AuthIntegrationsWhatsappIndexRoute: typeof AuthIntegrationsWhatsappIndexRoute
  AuthIntegrationsInstagramOnboardingTokenIdRoute: typeof AuthIntegrationsInstagramOnboardingTokenIdRoute
  AuthIntegrationsInstagramOnboardingNewRoute: typeof AuthIntegrationsInstagramOnboardingNewRoute
  AuthIntegrationsWhatsappOrgAddressIdProfileRoute: typeof AuthIntegrationsWhatsappOrgAddressIdProfileRoute
  AuthIntegrationsWhatsappOnboardingTokenIdRoute: typeof AuthIntegrationsWhatsappOnboardingTokenIdRoute
  AuthIntegrationsWhatsappOnboardingNewRoute: typeof AuthIntegrationsWhatsappOnboardingNewRoute
  AuthIntegrationsInstagramOrgAddressIdIndexRoute: typeof AuthIntegrationsInstagramOrgAddressIdIndexRoute
  AuthIntegrationsInstagramOnboardingIndexRoute: typeof AuthIntegrationsInstagramOnboardingIndexRoute
  AuthIntegrationsWhatsappOrgAddressIdIndexRoute: typeof AuthIntegrationsWhatsappOrgAddressIdIndexRoute
  AuthIntegrationsWhatsappOnboardingIndexRoute: typeof AuthIntegrationsWhatsappOnboardingIndexRoute
  AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRoute: typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRoute
  AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRoute: typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRoute
  AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRoute: typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthQuickRepliesRoute: AuthQuickRepliesRoute,
  AuthSettingsRoute: AuthSettingsRouteWithChildren,
  AuthStatsRoute: AuthStatsRouteWithChildren,
  AuthWhatsappManagerRoute: AuthWhatsappManagerRoute,
  AuthAgentsAgentIdRoute: AuthAgentsAgentIdRoute,
  AuthAgentsNewRoute: AuthAgentsNewRoute,
  AuthCampaignsCampaignIdRoute: AuthCampaignsCampaignIdRoute,
  AuthCampaignsNewRoute: AuthCampaignsNewRoute,
  AuthChatbotsFlowIdRoute: AuthChatbotsFlowIdRoute,
  AuthContactsContactIdRoute: AuthContactsContactIdRoute,
  AuthContactsNewRoute: AuthContactsNewRoute,
  AuthConversationsNewRoute: AuthConversationsNewRoute,
  AuthIntegrationsMediaPreprocessingRoute:
    AuthIntegrationsMediaPreprocessingRoute,
  AuthTemplatesTemplateIdRoute: AuthTemplatesTemplateIdRouteWithChildren,
  AuthTemplatesNewRoute: AuthTemplatesNewRoute,
  AuthAgentsIndexRoute: AuthAgentsIndexRoute,
  AuthCampaignsIndexRoute: AuthCampaignsIndexRoute,
  AuthChatbotsIndexRoute: AuthChatbotsIndexRoute,
  AuthContactsIndexRoute: AuthContactsIndexRoute,
  AuthConversationsIndexRoute: AuthConversationsIndexRoute,
  AuthIntegrationsIndexRoute: AuthIntegrationsIndexRoute,
  AuthTeamMembersIndexRoute: AuthTeamMembersIndexRoute,
  AuthTemplatesIndexRoute: AuthTemplatesIndexRoute,
  AuthCampaignsCampaignIdEditRoute: AuthCampaignsCampaignIdEditRoute,
  AuthCampaignsCampaignIdReviewRoute: AuthCampaignsCampaignIdReviewRoute,
  AuthIntegrationsInstagramNewRoute: AuthIntegrationsInstagramNewRoute,
  AuthIntegrationsWhatsappNewRoute: AuthIntegrationsWhatsappNewRoute,
  AuthIntegrationsInstagramIndexRoute: AuthIntegrationsInstagramIndexRoute,
  AuthIntegrationsWhatsappIndexRoute: AuthIntegrationsWhatsappIndexRoute,
  AuthIntegrationsInstagramOnboardingTokenIdRoute:
    AuthIntegrationsInstagramOnboardingTokenIdRoute,
  AuthIntegrationsInstagramOnboardingNewRoute:
    AuthIntegrationsInstagramOnboardingNewRoute,
  AuthIntegrationsWhatsappOrgAddressIdProfileRoute:
    AuthIntegrationsWhatsappOrgAddressIdProfileRoute,
  AuthIntegrationsWhatsappOnboardingTokenIdRoute:
    AuthIntegrationsWhatsappOnboardingTokenIdRoute,
  AuthIntegrationsWhatsappOnboardingNewRoute:
    AuthIntegrationsWhatsappOnboardingNewRoute,
  AuthIntegrationsInstagramOrgAddressIdIndexRoute:
    AuthIntegrationsInstagramOrgAddressIdIndexRoute,
  AuthIntegrationsInstagramOnboardingIndexRoute:
    AuthIntegrationsInstagramOnboardingIndexRoute,
  AuthIntegrationsWhatsappOrgAddressIdIndexRoute:
    AuthIntegrationsWhatsappOrgAddressIdIndexRoute,
  AuthIntegrationsWhatsappOnboardingIndexRoute:
    AuthIntegrationsWhatsappOnboardingIndexRoute,
  AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRoute:
    AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRoute,
  AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRoute:
    AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRoute,
  AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRoute:
    AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PlatformOrganizationIdRouteChildren {
  PlatformOrganizationIdReportsRoute: typeof PlatformOrganizationIdReportsRoute
  PlatformOrganizationIdIndexRoute: typeof PlatformOrganizationIdIndexRoute
}

const PlatformOrganizationIdRouteChildren: PlatformOrganizationIdRouteChildren =
  {
    PlatformOrganizationIdReportsRoute: PlatformOrganizationIdReportsRoute,
    PlatformOrganizationIdIndexRoute: PlatformOrganizationIdIndexRoute,
  }

const PlatformOrganizationIdRouteWithChildren =
  PlatformOrganizationIdRoute._addFileChildren(
    PlatformOrganizationIdRouteChildren,
  )

interface PlatformRouteChildren {
  PlatformOrganizationIdRoute: typeof PlatformOrganizationIdRouteWithChildren
  PlatformIndexRoute: typeof PlatformIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformOrganizationIdRoute: PlatformOrganizationIdRouteWithChildren,
  PlatformIndexRoute: PlatformIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DataDeletionRoute: DataDeletionRoute,
  LoginRoute: LoginRoute,
  PlatformRoute: PlatformRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  LoginEmailRoute: LoginEmailRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  OauthInstagramRoute: OauthInstagramRoute,
  OnboardInstagramTokenRoute: OnboardInstagramTokenRoute,
  OnboardInstagramCallbackRoute: OnboardInstagramCallbackRoute,
  OnboardWhatsappTokenRoute: OnboardWhatsappTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
