/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as OauthInstagramRouteImport } from './routes/oauth/instagram'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as LoginEmailRouteImport } from './routes/login_.email'
import { Route as AuthStatsRouteImport } from './routes/_auth/stats'
import { Route as AuthStatsIndexRouteImport } from './routes/_auth/stats/index'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthIntegrationsIndexRouteImport } from './routes/_auth/integrations/index'
import { Route as AuthConversationsIndexRouteImport } from './routes/_auth/conversations/index'
import { Route as AuthContactsIndexRouteImport } from './routes/_auth/contacts/index'
import { Route as AuthAgentsIndexRouteImport } from './routes/_auth/agents/index'
import { Route as OnboardWhatsappTokenRouteImport } from './routes/onboard.whatsapp.$token'
import { Route as OnboardInstagramCallbackRouteImport } from './routes/onboard.instagram.callback'
import { Route as OnboardInstagramTokenRouteImport } from './routes/onboard.instagram.$token'
import { Route as AuthStatsUsageRouteImport } from './routes/_auth/stats/usage'
import { Route as AuthStatsQuotasRouteImport } from './routes/_auth/stats/quotas'
import { Route as AuthIntegrationsMediaPreprocessingRouteImport } from './routes/_auth/integrations/media-preprocessing'
import { Route as AuthConversationsNewRouteImport } from './routes/_auth/conversations/new'
import { Route as AuthContactsNewRouteImport } from './routes/_auth/contacts/new'
import { Route as AuthContactsContactIdRouteImport } from './routes/_auth/contacts/$contactId'
import { Route as AuthAgentsNewRouteImport } from './routes/_auth/agents/new'
import { Route as AuthAgentsAgentIdRouteImport } from './routes/_auth/agents/$agentId'
import { Route as AuthSettingsWebhooksIndexRouteImport } from './routes/_auth/settings/webhooks/index'
import { Route as AuthSettingsOrganizationIndexRouteImport } from './routes/_auth/settings/organization/index'
import { Route as AuthSettingsMembersIndexRouteImport } from './routes/_auth/settings/members/index'
import { Route as AuthSettingsApiKeysIndexRouteImport } from './routes/_auth/settings/api-keys/index'
import { Route as AuthIntegrationsWhatsappIndexRouteImport } from './routes/_auth/integrations/whatsapp/index'
import { Route as AuthIntegrationsInstagramIndexRouteImport } from './routes/_auth/integrations/instagram/index'
import { Route as AuthSettingsWebhooksNewRouteImport } from './routes/_auth/settings/webhooks/new'
import { Route as AuthSettingsWebhooksWebhookIdRouteImport } from './routes/_auth/settings/webhooks/$webhookId'
import { Route as AuthSettingsOrganizationNewRouteImport } from './routes/_auth/settings/organization/new'
import { Route as AuthSettingsMembersNewRouteImport } from './routes/_auth/settings/members/new'
import { Route as AuthSettingsMembersMemberIdRouteImport } from './routes/_auth/settings/members/$memberId'
import { Route as AuthSettingsApiKeysNewRouteImport } from './routes/_auth/settings/api-keys/new'
import { Route as AuthSettingsApiKeysApiKeyIdRouteImport } from './routes/_auth/settings/api-keys/$apiKeyId'
import { Route as AuthIntegrationsWhatsappNewRouteImport } from './routes/_auth/integrations/whatsapp/new'
import { Route as AuthIntegrationsInstagramNewRouteImport } from './routes/_auth/integrations/instagram/new'
import { Route as AuthIntegrationsWhatsappOnboardingIndexRouteImport } from './routes/_auth/integrations/whatsapp/onboarding/index'
import { Route as AuthIntegrationsWhatsappOrgAddressIdIndexRouteImport } from './routes/_auth/integrations/whatsapp/$orgAddressId/index'
import { Route as AuthIntegrationsInstagramOnboardingIndexRouteImport } from './routes/_auth/integrations/instagram/onboarding/index'
import { Route as AuthIntegrationsInstagramOrgAddressIdIndexRouteImport } from './routes/_auth/integrations/instagram/$orgAddressId/index'
import { Route as AuthIntegrationsWhatsappOnboardingNewRouteImport } from './routes/_auth/integrations/whatsapp/onboarding/new'
import { Route as AuthIntegrationsWhatsappOnboardingTokenIdRouteImport } from './routes/_auth/integrations/whatsapp/onboarding/$tokenId'
import { Route as AuthIntegrationsInstagramOnboardingNewRouteImport } from './routes/_auth/integrations/instagram/onboarding/new'
import { Route as AuthIntegrationsInstagramOnboardingTokenIdRouteImport } from './routes/_auth/integrations/instagram/onboarding/$tokenId'
import { Route as AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRouteImport } from './routes/_auth/integrations/whatsapp/$orgAddressId/templates/index'
import { Route as AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRouteImport } from './routes/_auth/integrations/whatsapp/$orgAddressId/templates/new'
import { Route as AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRouteImport } from './routes/_auth/integrations/whatsapp/$orgAddressId/templates/$templateId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const OauthInstagramRoute = OauthInstagramRouteImport.update({
  id: '/oauth/instagram',
  path: '/oauth/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginEmailRoute = LoginEmailRouteImport.update({
  id: '/login_/email',
  path: '/login/email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStatsRoute = AuthStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStatsIndexRoute = AuthStatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthStatsRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthIntegrationsIndexRoute = AuthIntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConversationsIndexRoute = AuthConversationsIndexRouteImport.update({
  id: '/conversations/',
  path: '/conversations/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthContactsIndexRoute = AuthContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsIndexRoute = AuthAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AuthRoute,
} as any)
const OnboardWhatsappTokenRoute = OnboardWhatsappTokenRouteImport.update({
  id: '/onboard/whatsapp/$token',
  path: '/onboard/whatsapp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardInstagramCallbackRoute =
  OnboardInstagramCallbackRouteImport.update({
    id: '/onboard/instagram/callback',
    path: '/onboard/instagram/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnboardInstagramTokenRoute = OnboardInstagramTokenRouteImport.update({
  id: '/onboard/instagram/$token',
  path: '/onboard/instagram/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStatsUsageRoute = AuthStatsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthStatsRoute,
} as any)
const AuthStatsQuotasRoute = AuthStatsQuotasRouteImport.update({
  id: '/quotas',
  path: '/quotas',
  getParentRoute: () => AuthStatsRoute,
} as any)
const AuthIntegrationsMediaPreprocessingRoute =
  AuthIntegrationsMediaPreprocessingRouteImport.update({
    id: '/integrations/media-preprocessing',
    path: '/integrations/media-preprocessing',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthConversationsNewRoute = AuthConversationsNewRouteImport.update({
  id: '/conversations/new',
  path: '/conversations/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthContactsNewRoute = AuthContactsNewRouteImport.update({
  id: '/contacts/new',
  path: '/contacts/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthContactsContactIdRoute = AuthContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsNewRoute = AuthAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsAgentIdRoute = AuthAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsWebhooksIndexRoute =
  AuthSettingsWebhooksIndexRouteImport.update({
    id: '/settings/webhooks/',
    path: '/settings/webhooks/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsOrganizationIndexRoute =
  AuthSettingsOrganizationIndexRouteImport.update({
    id: '/settings/organization/',
    path: '/settings/organization/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsMembersIndexRoute =
  AuthSettingsMembersIndexRouteImport.update({
    id: '/settings/members/',
    path: '/settings/members/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsApiKeysIndexRoute =
  AuthSettingsApiKeysIndexRouteImport.update({
    id: '/settings/api-keys/',
    path: '/settings/api-keys/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsWhatsappIndexRoute =
  AuthIntegrationsWhatsappIndexRouteImport.update({
    id: '/integrations/whatsapp/',
    path: '/integrations/whatsapp/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsInstagramIndexRoute =
  AuthIntegrationsInstagramIndexRouteImport.update({
    id: '/integrations/instagram/',
    path: '/integrations/instagram/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsWebhooksNewRoute = AuthSettingsWebhooksNewRouteImport.update({
  id: '/settings/webhooks/new',
  path: '/settings/webhooks/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsWebhooksWebhookIdRoute =
  AuthSettingsWebhooksWebhookIdRouteImport.update({
    id: '/settings/webhooks/$webhookId',
    path: '/settings/webhooks/$webhookId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsOrganizationNewRoute =
  AuthSettingsOrganizationNewRouteImport.update({
    id: '/settings/organization/new',
    path: '/settings/organization/new',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsMembersNewRoute = AuthSettingsMembersNewRouteImport.update({
  id: '/settings/members/new',
  path: '/settings/members/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsMembersMemberIdRoute =
  AuthSettingsMembersMemberIdRouteImport.update({
    id: '/settings/members/$memberId',
    path: '/settings/members/$memberId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsApiKeysNewRoute = AuthSettingsApiKeysNewRouteImport.update({
  id: '/settings/api-keys/new',
  path: '/settings/api-keys/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsApiKeysApiKeyIdRoute =
  AuthSettingsApiKeysApiKeyIdRouteImport.update({
    id: '/settings/api-keys/$apiKeyId',
    path: '/settings/api-keys/$apiKeyId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsWhatsappNewRoute =
  AuthIntegrationsWhatsappNewRouteImport.update({
    id: '/integrations/whatsapp/new',
    path: '/integrations/whatsapp/new',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsInstagramNewRoute =
  AuthIntegrationsInstagramNewRouteImport.update({
    id: '/integrations/instagram/new',
    path: '/integrations/instagram/new',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsWhatsappOnboardingIndexRoute =
  AuthIntegrationsWhatsappOnboardingIndexRouteImport.update({
    id: '/integrations/whatsapp/onboarding/',
    path: '/integrations/whatsapp/onboarding/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsWhatsappOrgAddressIdIndexRoute =
  AuthIntegrationsWhatsappOrgAddressIdIndexRouteImport.update({
    id: '/integrations/whatsapp/$orgAddressId/',
    path: '/integrations/whatsapp/$orgAddressId/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsInstagramOnboardingIndexRoute =
  AuthIntegrationsInstagramOnboardingIndexRouteImport.update({
    id: '/integrations/instagram/onboarding/',
    path: '/integrations/instagram/onboarding/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsInstagramOrgAddressIdIndexRoute =
  AuthIntegrationsInstagramOrgAddressIdIndexRouteImport.update({
    id: '/integrations/instagram/$orgAddressId/',
    path: '/integrations/instagram/$orgAddressId/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsWhatsappOnboardingNewRoute =
  AuthIntegrationsWhatsappOnboardingNewRouteImport.update({
    id: '/integrations/whatsapp/onboarding/new',
    path: '/integrations/whatsapp/onboarding/new',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsWhatsappOnboardingTokenIdRoute =
  AuthIntegrationsWhatsappOnboardingTokenIdRouteImport.update({
    id: '/integrations/whatsapp/onboarding/$tokenId',
    path: '/integrations/whatsapp/onboarding/$tokenId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsInstagramOnboardingNewRoute =
  AuthIntegrationsInstagramOnboardingNewRouteImport.update({
    id: '/integrations/instagram/onboarding/new',
    path: '/integrations/instagram/onboarding/new',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsInstagramOnboardingTokenIdRoute =
  AuthIntegrationsInstagramOnboardingTokenIdRouteImport.update({
    id: '/integrations/instagram/onboarding/$tokenId',
    path: '/integrations/instagram/onboarding/$tokenId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRoute =
  AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRouteImport.update({
    id: '/integrations/whatsapp/$orgAddressId/templates/',
    path: '/integrations/whatsapp/$orgAddressId/templates/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRoute =
  AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRouteImport.update({
    id: '/integrations/whatsapp/$orgAddressId/templates/new',
    path: '/integrations/whatsapp/$orgAddressId/templates/new',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRoute =
  AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRouteImport.update({
    id: '/integrations/whatsapp/$orgAddressId/templates/$templateId',
    path: '/integrations/whatsapp/$orgAddressId/templates/$templateId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/stats': typeof AuthStatsRouteWithChildren
  '/login/email': typeof LoginEmailRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/instagram': typeof OauthInstagramRoute
  '/': typeof AuthIndexRoute
  '/agents/$agentId': typeof AuthAgentsAgentIdRoute
  '/agents/new': typeof AuthAgentsNewRoute
  '/contacts/$contactId': typeof AuthContactsContactIdRoute
  '/contacts/new': typeof AuthContactsNewRoute
  '/conversations/new': typeof AuthConversationsNewRoute
  '/integrations/media-preprocessing': typeof AuthIntegrationsMediaPreprocessingRoute
  '/stats/quotas': typeof AuthStatsQuotasRoute
  '/stats/usage': typeof AuthStatsUsageRoute
  '/onboard/instagram/$token': typeof OnboardInstagramTokenRoute
  '/onboard/instagram/callback': typeof OnboardInstagramCallbackRoute
  '/onboard/whatsapp/$token': typeof OnboardWhatsappTokenRoute
  '/agents': typeof AuthAgentsIndexRoute
  '/contacts': typeof AuthContactsIndexRoute
  '/conversations': typeof AuthConversationsIndexRoute
  '/integrations': typeof AuthIntegrationsIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/stats/': typeof AuthStatsIndexRoute
  '/integrations/instagram/new': typeof AuthIntegrationsInstagramNewRoute
  '/integrations/whatsapp/new': typeof AuthIntegrationsWhatsappNewRoute
  '/settings/api-keys/$apiKeyId': typeof AuthSettingsApiKeysApiKeyIdRoute
  '/settings/api-keys/new': typeof AuthSettingsApiKeysNewRoute
  '/settings/members/$memberId': typeof AuthSettingsMembersMemberIdRoute
  '/settings/members/new': typeof AuthSettingsMembersNewRoute
  '/settings/organization/new': typeof AuthSettingsOrganizationNewRoute
  '/settings/webhooks/$webhookId': typeof AuthSettingsWebhooksWebhookIdRoute
  '/settings/webhooks/new': typeof AuthSettingsWebhooksNewRoute
  '/integrations/instagram': typeof AuthIntegrationsInstagramIndexRoute
  '/integrations/whatsapp': typeof AuthIntegrationsWhatsappIndexRoute
  '/settings/api-keys': typeof AuthSettingsApiKeysIndexRoute
  '/settings/members': typeof AuthSettingsMembersIndexRoute
  '/settings/organization': typeof AuthSettingsOrganizationIndexRoute
  '/settings/webhooks': typeof AuthSettingsWebhooksIndexRoute
  '/integrations/instagram/onboarding/$tokenId': typeof AuthIntegrationsInstagramOnboardingTokenIdRoute
  '/integrations/instagram/onboarding/new': typeof AuthIntegrationsInstagramOnboardingNewRoute
  '/integrations/whatsapp/onboarding/$tokenId': typeof AuthIntegrationsWhatsappOnboardingTokenIdRoute
  '/integrations/whatsapp/onboarding/new': typeof AuthIntegrationsWhatsappOnboardingNewRoute
  '/integrations/instagram/$orgAddressId': typeof AuthIntegrationsInstagramOrgAddressIdIndexRoute
  '/integrations/instagram/onboarding': typeof AuthIntegrationsInstagramOnboardingIndexRoute
  '/integrations/whatsapp/$orgAddressId': typeof AuthIntegrationsWhatsappOrgAddressIdIndexRoute
  '/integrations/whatsapp/onboarding': typeof AuthIntegrationsWhatsappOnboardingIndexRoute
  '/integrations/whatsapp/$orgAddressId/templates/$templateId': typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRoute
  '/integrations/whatsapp/$orgAddressId/templates/new': typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRoute
  '/integrations/whatsapp/$orgAddressId/templates': typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/login/email': typeof LoginEmailRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/instagram': typeof OauthInstagramRoute
  '/': typeof AuthIndexRoute
  '/agents/$agentId': typeof AuthAgentsAgentIdRoute
  '/agents/new': typeof AuthAgentsNewRoute
  '/contacts/$contactId': typeof AuthContactsContactIdRoute
  '/contacts/new': typeof AuthContactsNewRoute
  '/conversations/new': typeof AuthConversationsNewRoute
  '/integrations/media-preprocessing': typeof AuthIntegrationsMediaPreprocessingRoute
  '/stats/quotas': typeof AuthStatsQuotasRoute
  '/stats/usage': typeof AuthStatsUsageRoute
  '/onboard/instagram/$token': typeof OnboardInstagramTokenRoute
  '/onboard/instagram/callback': typeof OnboardInstagramCallbackRoute
  '/onboard/whatsapp/$token': typeof OnboardWhatsappTokenRoute
  '/agents': typeof AuthAgentsIndexRoute
  '/contacts': typeof AuthContactsIndexRoute
  '/conversations': typeof AuthConversationsIndexRoute
  '/integrations': typeof AuthIntegrationsIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/stats': typeof AuthStatsIndexRoute
  '/integrations/instagram/new': typeof AuthIntegrationsInstagramNewRoute
  '/integrations/whatsapp/new': typeof AuthIntegrationsWhatsappNewRoute
  '/settings/api-keys/$apiKeyId': typeof AuthSettingsApiKeysApiKeyIdRoute
  '/settings/api-keys/new': typeof AuthSettingsApiKeysNewRoute
  '/settings/members/$memberId': typeof AuthSettingsMembersMemberIdRoute
  '/settings/members/new': typeof AuthSettingsMembersNewRoute
  '/settings/organization/new': typeof AuthSettingsOrganizationNewRoute
  '/settings/webhooks/$webhookId': typeof AuthSettingsWebhooksWebhookIdRoute
  '/settings/webhooks/new': typeof AuthSettingsWebhooksNewRoute
  '/integrations/instagram': typeof AuthIntegrationsInstagramIndexRoute
  '/integrations/whatsapp': typeof AuthIntegrationsWhatsappIndexRoute
  '/settings/api-keys': typeof AuthSettingsApiKeysIndexRoute
  '/settings/members': typeof AuthSettingsMembersIndexRoute
  '/settings/organization': typeof AuthSettingsOrganizationIndexRoute
  '/settings/webhooks': typeof AuthSettingsWebhooksIndexRoute
  '/integrations/instagram/onboarding/$tokenId': typeof AuthIntegrationsInstagramOnboardingTokenIdRoute
  '/integrations/instagram/onboarding/new': typeof AuthIntegrationsInstagramOnboardingNewRoute
  '/integrations/whatsapp/onboarding/$tokenId': typeof AuthIntegrationsWhatsappOnboardingTokenIdRoute
  '/integrations/whatsapp/onboarding/new': typeof AuthIntegrationsWhatsappOnboardingNewRoute
  '/integrations/instagram/$orgAddressId': typeof AuthIntegrationsInstagramOrgAddressIdIndexRoute
  '/integrations/instagram/onboarding': typeof AuthIntegrationsInstagramOnboardingIndexRoute
  '/integrations/whatsapp/$orgAddressId': typeof AuthIntegrationsWhatsappOrgAddressIdIndexRoute
  '/integrations/whatsapp/onboarding': typeof AuthIntegrationsWhatsappOnboardingIndexRoute
  '/integrations/whatsapp/$orgAddressId/templates/$templateId': typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRoute
  '/integrations/whatsapp/$orgAddressId/templates/new': typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRoute
  '/integrations/whatsapp/$orgAddressId/templates': typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/stats': typeof AuthStatsRouteWithChildren
  '/login_/email': typeof LoginEmailRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/instagram': typeof OauthInstagramRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/agents/$agentId': typeof AuthAgentsAgentIdRoute
  '/_auth/agents/new': typeof AuthAgentsNewRoute
  '/_auth/contacts/$contactId': typeof AuthContactsContactIdRoute
  '/_auth/contacts/new': typeof AuthContactsNewRoute
  '/_auth/conversations/new': typeof AuthConversationsNewRoute
  '/_auth/integrations/media-preprocessing': typeof AuthIntegrationsMediaPreprocessingRoute
  '/_auth/stats/quotas': typeof AuthStatsQuotasRoute
  '/_auth/stats/usage': typeof AuthStatsUsageRoute
  '/onboard/instagram/$token': typeof OnboardInstagramTokenRoute
  '/onboard/instagram/callback': typeof OnboardInstagramCallbackRoute
  '/onboard/whatsapp/$token': typeof OnboardWhatsappTokenRoute
  '/_auth/agents/': typeof AuthAgentsIndexRoute
  '/_auth/contacts/': typeof AuthContactsIndexRoute
  '/_auth/conversations/': typeof AuthConversationsIndexRoute
  '/_auth/integrations/': typeof AuthIntegrationsIndexRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/stats/': typeof AuthStatsIndexRoute
  '/_auth/integrations/instagram/new': typeof AuthIntegrationsInstagramNewRoute
  '/_auth/integrations/whatsapp/new': typeof AuthIntegrationsWhatsappNewRoute
  '/_auth/settings/api-keys/$apiKeyId': typeof AuthSettingsApiKeysApiKeyIdRoute
  '/_auth/settings/api-keys/new': typeof AuthSettingsApiKeysNewRoute
  '/_auth/settings/members/$memberId': typeof AuthSettingsMembersMemberIdRoute
  '/_auth/settings/members/new': typeof AuthSettingsMembersNewRoute
  '/_auth/settings/organization/new': typeof AuthSettingsOrganizationNewRoute
  '/_auth/settings/webhooks/$webhookId': typeof AuthSettingsWebhooksWebhookIdRoute
  '/_auth/settings/webhooks/new': typeof AuthSettingsWebhooksNewRoute
  '/_auth/integrations/instagram/': typeof AuthIntegrationsInstagramIndexRoute
  '/_auth/integrations/whatsapp/': typeof AuthIntegrationsWhatsappIndexRoute
  '/_auth/settings/api-keys/': typeof AuthSettingsApiKeysIndexRoute
  '/_auth/settings/members/': typeof AuthSettingsMembersIndexRoute
  '/_auth/settings/organization/': typeof AuthSettingsOrganizationIndexRoute
  '/_auth/settings/webhooks/': typeof AuthSettingsWebhooksIndexRoute
  '/_auth/integrations/instagram/onboarding/$tokenId': typeof AuthIntegrationsInstagramOnboardingTokenIdRoute
  '/_auth/integrations/instagram/onboarding/new': typeof AuthIntegrationsInstagramOnboardingNewRoute
  '/_auth/integrations/whatsapp/onboarding/$tokenId': typeof AuthIntegrationsWhatsappOnboardingTokenIdRoute
  '/_auth/integrations/whatsapp/onboarding/new': typeof AuthIntegrationsWhatsappOnboardingNewRoute
  '/_auth/integrations/instagram/$orgAddressId/': typeof AuthIntegrationsInstagramOrgAddressIdIndexRoute
  '/_auth/integrations/instagram/onboarding/': typeof AuthIntegrationsInstagramOnboardingIndexRoute
  '/_auth/integrations/whatsapp/$orgAddressId/': typeof AuthIntegrationsWhatsappOrgAddressIdIndexRoute
  '/_auth/integrations/whatsapp/onboarding/': typeof AuthIntegrationsWhatsappOnboardingIndexRoute
  '/_auth/integrations/whatsapp/$orgAddressId/templates/$templateId': typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRoute
  '/_auth/integrations/whatsapp/$orgAddressId/templates/new': typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRoute
  '/_auth/integrations/whatsapp/$orgAddressId/templates/': typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/stats'
    | '/login/email'
    | '/oauth/callback'
    | '/oauth/instagram'
    | '/'
    | '/agents/$agentId'
    | '/agents/new'
    | '/contacts/$contactId'
    | '/contacts/new'
    | '/conversations/new'
    | '/integrations/media-preprocessing'
    | '/stats/quotas'
    | '/stats/usage'
    | '/onboard/instagram/$token'
    | '/onboard/instagram/callback'
    | '/onboard/whatsapp/$token'
    | '/agents'
    | '/contacts'
    | '/conversations'
    | '/integrations'
    | '/settings'
    | '/stats/'
    | '/integrations/instagram/new'
    | '/integrations/whatsapp/new'
    | '/settings/api-keys/$apiKeyId'
    | '/settings/api-keys/new'
    | '/settings/members/$memberId'
    | '/settings/members/new'
    | '/settings/organization/new'
    | '/settings/webhooks/$webhookId'
    | '/settings/webhooks/new'
    | '/integrations/instagram'
    | '/integrations/whatsapp'
    | '/settings/api-keys'
    | '/settings/members'
    | '/settings/organization'
    | '/settings/webhooks'
    | '/integrations/instagram/onboarding/$tokenId'
    | '/integrations/instagram/onboarding/new'
    | '/integrations/whatsapp/onboarding/$tokenId'
    | '/integrations/whatsapp/onboarding/new'
    | '/integrations/instagram/$orgAddressId'
    | '/integrations/instagram/onboarding'
    | '/integrations/whatsapp/$orgAddressId'
    | '/integrations/whatsapp/onboarding'
    | '/integrations/whatsapp/$orgAddressId/templates/$templateId'
    | '/integrations/whatsapp/$orgAddressId/templates/new'
    | '/integrations/whatsapp/$orgAddressId/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/login/email'
    | '/oauth/callback'
    | '/oauth/instagram'
    | '/'
    | '/agents/$agentId'
    | '/agents/new'
    | '/contacts/$contactId'
    | '/contacts/new'
    | '/conversations/new'
    | '/integrations/media-preprocessing'
    | '/stats/quotas'
    | '/stats/usage'
    | '/onboard/instagram/$token'
    | '/onboard/instagram/callback'
    | '/onboard/whatsapp/$token'
    | '/agents'
    | '/contacts'
    | '/conversations'
    | '/integrations'
    | '/settings'
    | '/stats'
    | '/integrations/instagram/new'
    | '/integrations/whatsapp/new'
    | '/settings/api-keys/$apiKeyId'
    | '/settings/api-keys/new'
    | '/settings/members/$memberId'
    | '/settings/members/new'
    | '/settings/organization/new'
    | '/settings/webhooks/$webhookId'
    | '/settings/webhooks/new'
    | '/integrations/instagram'
    | '/integrations/whatsapp'
    | '/settings/api-keys'
    | '/settings/members'
    | '/settings/organization'
    | '/settings/webhooks'
    | '/integrations/instagram/onboarding/$tokenId'
    | '/integrations/instagram/onboarding/new'
    | '/integrations/whatsapp/onboarding/$tokenId'
    | '/integrations/whatsapp/onboarding/new'
    | '/integrations/instagram/$orgAddressId'
    | '/integrations/instagram/onboarding'
    | '/integrations/whatsapp/$orgAddressId'
    | '/integrations/whatsapp/onboarding'
    | '/integrations/whatsapp/$orgAddressId/templates/$templateId'
    | '/integrations/whatsapp/$orgAddressId/templates/new'
    | '/integrations/whatsapp/$orgAddressId/templates'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/stats'
    | '/login_/email'
    | '/oauth/callback'
    | '/oauth/instagram'
    | '/_auth/'
    | '/_auth/agents/$agentId'
    | '/_auth/agents/new'
    | '/_auth/contacts/$contactId'
    | '/_auth/contacts/new'
    | '/_auth/conversations/new'
    | '/_auth/integrations/media-preprocessing'
    | '/_auth/stats/quotas'
    | '/_auth/stats/usage'
    | '/onboard/instagram/$token'
    | '/onboard/instagram/callback'
    | '/onboard/whatsapp/$token'
    | '/_auth/agents/'
    | '/_auth/contacts/'
    | '/_auth/conversations/'
    | '/_auth/integrations/'
    | '/_auth/settings/'
    | '/_auth/stats/'
    | '/_auth/integrations/instagram/new'
    | '/_auth/integrations/whatsapp/new'
    | '/_auth/settings/api-keys/$apiKeyId'
    | '/_auth/settings/api-keys/new'
    | '/_auth/settings/members/$memberId'
    | '/_auth/settings/members/new'
    | '/_auth/settings/organization/new'
    | '/_auth/settings/webhooks/$webhookId'
    | '/_auth/settings/webhooks/new'
    | '/_auth/integrations/instagram/'
    | '/_auth/integrations/whatsapp/'
    | '/_auth/settings/api-keys/'
    | '/_auth/settings/members/'
    | '/_auth/settings/organization/'
    | '/_auth/settings/webhooks/'
    | '/_auth/integrations/instagram/onboarding/$tokenId'
    | '/_auth/integrations/instagram/onboarding/new'
    | '/_auth/integrations/whatsapp/onboarding/$tokenId'
    | '/_auth/integrations/whatsapp/onboarding/new'
    | '/_auth/integrations/instagram/$orgAddressId/'
    | '/_auth/integrations/instagram/onboarding/'
    | '/_auth/integrations/whatsapp/$orgAddressId/'
    | '/_auth/integrations/whatsapp/onboarding/'
    | '/_auth/integrations/whatsapp/$orgAddressId/templates/$templateId'
    | '/_auth/integrations/whatsapp/$orgAddressId/templates/new'
    | '/_auth/integrations/whatsapp/$orgAddressId/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  LoginEmailRoute: typeof LoginEmailRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  OauthInstagramRoute: typeof OauthInstagramRoute
  OnboardInstagramTokenRoute: typeof OnboardInstagramTokenRoute
  OnboardInstagramCallbackRoute: typeof OnboardInstagramCallbackRoute
  OnboardWhatsappTokenRoute: typeof OnboardWhatsappTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/oauth/instagram': {
      id: '/oauth/instagram'
      path: '/oauth/instagram'
      fullPath: '/oauth/instagram'
      preLoaderRoute: typeof OauthInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/email': {
      id: '/login_/email'
      path: '/login/email'
      fullPath: '/login/email'
      preLoaderRoute: typeof LoginEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/stats': {
      id: '/_auth/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthStatsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/stats/': {
      id: '/_auth/stats/'
      path: '/'
      fullPath: '/stats/'
      preLoaderRoute: typeof AuthStatsIndexRouteImport
      parentRoute: typeof AuthStatsRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/': {
      id: '/_auth/integrations/'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthIntegrationsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/conversations/': {
      id: '/_auth/conversations/'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthConversationsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/contacts/': {
      id: '/_auth/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthContactsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents/': {
      id: '/_auth/agents/'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthAgentsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/onboard/whatsapp/$token': {
      id: '/onboard/whatsapp/$token'
      path: '/onboard/whatsapp/$token'
      fullPath: '/onboard/whatsapp/$token'
      preLoaderRoute: typeof OnboardWhatsappTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard/instagram/callback': {
      id: '/onboard/instagram/callback'
      path: '/onboard/instagram/callback'
      fullPath: '/onboard/instagram/callback'
      preLoaderRoute: typeof OnboardInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard/instagram/$token': {
      id: '/onboard/instagram/$token'
      path: '/onboard/instagram/$token'
      fullPath: '/onboard/instagram/$token'
      preLoaderRoute: typeof OnboardInstagramTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/stats/usage': {
      id: '/_auth/stats/usage'
      path: '/usage'
      fullPath: '/stats/usage'
      preLoaderRoute: typeof AuthStatsUsageRouteImport
      parentRoute: typeof AuthStatsRoute
    }
    '/_auth/stats/quotas': {
      id: '/_auth/stats/quotas'
      path: '/quotas'
      fullPath: '/stats/quotas'
      preLoaderRoute: typeof AuthStatsQuotasRouteImport
      parentRoute: typeof AuthStatsRoute
    }
    '/_auth/integrations/media-preprocessing': {
      id: '/_auth/integrations/media-preprocessing'
      path: '/integrations/media-preprocessing'
      fullPath: '/integrations/media-preprocessing'
      preLoaderRoute: typeof AuthIntegrationsMediaPreprocessingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/conversations/new': {
      id: '/_auth/conversations/new'
      path: '/conversations/new'
      fullPath: '/conversations/new'
      preLoaderRoute: typeof AuthConversationsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/contacts/new': {
      id: '/_auth/contacts/new'
      path: '/contacts/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof AuthContactsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/contacts/$contactId': {
      id: '/_auth/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof AuthContactsContactIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents/new': {
      id: '/_auth/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AuthAgentsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents/$agentId': {
      id: '/_auth/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthAgentsAgentIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/webhooks/': {
      id: '/_auth/settings/webhooks/'
      path: '/settings/webhooks'
      fullPath: '/settings/webhooks'
      preLoaderRoute: typeof AuthSettingsWebhooksIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/organization/': {
      id: '/_auth/settings/organization/'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthSettingsOrganizationIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/members/': {
      id: '/_auth/settings/members/'
      path: '/settings/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AuthSettingsMembersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/api-keys/': {
      id: '/_auth/settings/api-keys/'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthSettingsApiKeysIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/whatsapp/': {
      id: '/_auth/integrations/whatsapp/'
      path: '/integrations/whatsapp'
      fullPath: '/integrations/whatsapp'
      preLoaderRoute: typeof AuthIntegrationsWhatsappIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/instagram/': {
      id: '/_auth/integrations/instagram/'
      path: '/integrations/instagram'
      fullPath: '/integrations/instagram'
      preLoaderRoute: typeof AuthIntegrationsInstagramIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/webhooks/new': {
      id: '/_auth/settings/webhooks/new'
      path: '/settings/webhooks/new'
      fullPath: '/settings/webhooks/new'
      preLoaderRoute: typeof AuthSettingsWebhooksNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/webhooks/$webhookId': {
      id: '/_auth/settings/webhooks/$webhookId'
      path: '/settings/webhooks/$webhookId'
      fullPath: '/settings/webhooks/$webhookId'
      preLoaderRoute: typeof AuthSettingsWebhooksWebhookIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/organization/new': {
      id: '/_auth/settings/organization/new'
      path: '/settings/organization/new'
      fullPath: '/settings/organization/new'
      preLoaderRoute: typeof AuthSettingsOrganizationNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/members/new': {
      id: '/_auth/settings/members/new'
      path: '/settings/members/new'
      fullPath: '/settings/members/new'
      preLoaderRoute: typeof AuthSettingsMembersNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/members/$memberId': {
      id: '/_auth/settings/members/$memberId'
      path: '/settings/members/$memberId'
      fullPath: '/settings/members/$memberId'
      preLoaderRoute: typeof AuthSettingsMembersMemberIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/api-keys/new': {
      id: '/_auth/settings/api-keys/new'
      path: '/settings/api-keys/new'
      fullPath: '/settings/api-keys/new'
      preLoaderRoute: typeof AuthSettingsApiKeysNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/api-keys/$apiKeyId': {
      id: '/_auth/settings/api-keys/$apiKeyId'
      path: '/settings/api-keys/$apiKeyId'
      fullPath: '/settings/api-keys/$apiKeyId'
      preLoaderRoute: typeof AuthSettingsApiKeysApiKeyIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/whatsapp/new': {
      id: '/_auth/integrations/whatsapp/new'
      path: '/integrations/whatsapp/new'
      fullPath: '/integrations/whatsapp/new'
      preLoaderRoute: typeof AuthIntegrationsWhatsappNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/instagram/new': {
      id: '/_auth/integrations/instagram/new'
      path: '/integrations/instagram/new'
      fullPath: '/integrations/instagram/new'
      preLoaderRoute: typeof AuthIntegrationsInstagramNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/whatsapp/onboarding/': {
      id: '/_auth/integrations/whatsapp/onboarding/'
      path: '/integrations/whatsapp/onboarding'
      fullPath: '/integrations/whatsapp/onboarding'
      preLoaderRoute: typeof AuthIntegrationsWhatsappOnboardingIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/whatsapp/$orgAddressId/': {
      id: '/_auth/integrations/whatsapp/$orgAddressId/'
      path: '/integrations/whatsapp/$orgAddressId'
      fullPath: '/integrations/whatsapp/$orgAddressId'
      preLoaderRoute: typeof AuthIntegrationsWhatsappOrgAddressIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/instagram/onboarding/': {
      id: '/_auth/integrations/instagram/onboarding/'
      path: '/integrations/instagram/onboarding'
      fullPath: '/integrations/instagram/onboarding'
      preLoaderRoute: typeof AuthIntegrationsInstagramOnboardingIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/instagram/$orgAddressId/': {
      id: '/_auth/integrations/instagram/$orgAddressId/'
      path: '/integrations/instagram/$orgAddressId'
      fullPath: '/integrations/instagram/$orgAddressId'
      preLoaderRoute: typeof AuthIntegrationsInstagramOrgAddressIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/whatsapp/onboarding/new': {
      id: '/_auth/integrations/whatsapp/onboarding/new'
      path: '/integrations/whatsapp/onboarding/new'
      fullPath: '/integrations/whatsapp/onboarding/new'
      preLoaderRoute: typeof AuthIntegrationsWhatsappOnboardingNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/whatsapp/onboarding/$tokenId': {
      id: '/_auth/integrations/whatsapp/onboarding/$tokenId'
      path: '/integrations/whatsapp/onboarding/$tokenId'
      fullPath: '/integrations/whatsapp/onboarding/$tokenId'
      preLoaderRoute: typeof AuthIntegrationsWhatsappOnboardingTokenIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/instagram/onboarding/new': {
      id: '/_auth/integrations/instagram/onboarding/new'
      path: '/integrations/instagram/onboarding/new'
      fullPath: '/integrations/instagram/onboarding/new'
      preLoaderRoute: typeof AuthIntegrationsInstagramOnboardingNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/instagram/onboarding/$tokenId': {
      id: '/_auth/integrations/instagram/onboarding/$tokenId'
      path: '/integrations/instagram/onboarding/$tokenId'
      fullPath: '/integrations/instagram/onboarding/$tokenId'
      preLoaderRoute: typeof AuthIntegrationsInstagramOnboardingTokenIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/whatsapp/$orgAddressId/templates/': {
      id: '/_auth/integrations/whatsapp/$orgAddressId/templates/'
      path: '/integrations/whatsapp/$orgAddressId/templates'
      fullPath: '/integrations/whatsapp/$orgAddressId/templates'
      preLoaderRoute: typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/whatsapp/$orgAddressId/templates/new': {
      id: '/_auth/integrations/whatsapp/$orgAddressId/templates/new'
      path: '/integrations/whatsapp/$orgAddressId/templates/new'
      fullPath: '/integrations/whatsapp/$orgAddressId/templates/new'
      preLoaderRoute: typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/integrations/whatsapp/$orgAddressId/templates/$templateId': {
      id: '/_auth/integrations/whatsapp/$orgAddressId/templates/$templateId'
      path: '/integrations/whatsapp/$orgAddressId/templates/$templateId'
      fullPath: '/integrations/whatsapp/$orgAddressId/templates/$templateId'
      preLoaderRoute: typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthStatsRouteChildren {
  AuthStatsQuotasRoute: typeof AuthStatsQuotasRoute
  AuthStatsUsageRoute: typeof AuthStatsUsageRoute
  AuthStatsIndexRoute: typeof AuthStatsIndexRoute
}

const AuthStatsRouteChildren: AuthStatsRouteChildren = {
  AuthStatsQuotasRoute: AuthStatsQuotasRoute,
  AuthStatsUsageRoute: AuthStatsUsageRoute,
  AuthStatsIndexRoute: AuthStatsIndexRoute,
}

const AuthStatsRouteWithChildren = AuthStatsRoute._addFileChildren(
  AuthStatsRouteChildren,
)

interface AuthRouteChildren {
  AuthStatsRoute: typeof AuthStatsRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAgentsAgentIdRoute: typeof AuthAgentsAgentIdRoute
  AuthAgentsNewRoute: typeof AuthAgentsNewRoute
  AuthContactsContactIdRoute: typeof AuthContactsContactIdRoute
  AuthContactsNewRoute: typeof AuthContactsNewRoute
  AuthConversationsNewRoute: typeof AuthConversationsNewRoute
  AuthIntegrationsMediaPreprocessingRoute: typeof AuthIntegrationsMediaPreprocessingRoute
  AuthAgentsIndexRoute: typeof AuthAgentsIndexRoute
  AuthContactsIndexRoute: typeof AuthContactsIndexRoute
  AuthConversationsIndexRoute: typeof AuthConversationsIndexRoute
  AuthIntegrationsIndexRoute: typeof AuthIntegrationsIndexRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
  AuthIntegrationsInstagramNewRoute: typeof AuthIntegrationsInstagramNewRoute
  AuthIntegrationsWhatsappNewRoute: typeof AuthIntegrationsWhatsappNewRoute
  AuthSettingsApiKeysApiKeyIdRoute: typeof AuthSettingsApiKeysApiKeyIdRoute
  AuthSettingsApiKeysNewRoute: typeof AuthSettingsApiKeysNewRoute
  AuthSettingsMembersMemberIdRoute: typeof AuthSettingsMembersMemberIdRoute
  AuthSettingsMembersNewRoute: typeof AuthSettingsMembersNewRoute
  AuthSettingsOrganizationNewRoute: typeof AuthSettingsOrganizationNewRoute
  AuthSettingsWebhooksWebhookIdRoute: typeof AuthSettingsWebhooksWebhookIdRoute
  AuthSettingsWebhooksNewRoute: typeof AuthSettingsWebhooksNewRoute
  AuthIntegrationsInstagramIndexRoute: typeof AuthIntegrationsInstagramIndexRoute
  AuthIntegrationsWhatsappIndexRoute: typeof AuthIntegrationsWhatsappIndexRoute
  AuthSettingsApiKeysIndexRoute: typeof AuthSettingsApiKeysIndexRoute
  AuthSettingsMembersIndexRoute: typeof AuthSettingsMembersIndexRoute
  AuthSettingsOrganizationIndexRoute: typeof AuthSettingsOrganizationIndexRoute
  AuthSettingsWebhooksIndexRoute: typeof AuthSettingsWebhooksIndexRoute
  AuthIntegrationsInstagramOnboardingTokenIdRoute: typeof AuthIntegrationsInstagramOnboardingTokenIdRoute
  AuthIntegrationsInstagramOnboardingNewRoute: typeof AuthIntegrationsInstagramOnboardingNewRoute
  AuthIntegrationsWhatsappOnboardingTokenIdRoute: typeof AuthIntegrationsWhatsappOnboardingTokenIdRoute
  AuthIntegrationsWhatsappOnboardingNewRoute: typeof AuthIntegrationsWhatsappOnboardingNewRoute
  AuthIntegrationsInstagramOrgAddressIdIndexRoute: typeof AuthIntegrationsInstagramOrgAddressIdIndexRoute
  AuthIntegrationsInstagramOnboardingIndexRoute: typeof AuthIntegrationsInstagramOnboardingIndexRoute
  AuthIntegrationsWhatsappOrgAddressIdIndexRoute: typeof AuthIntegrationsWhatsappOrgAddressIdIndexRoute
  AuthIntegrationsWhatsappOnboardingIndexRoute: typeof AuthIntegrationsWhatsappOnboardingIndexRoute
  AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRoute: typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRoute
  AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRoute: typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRoute
  AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRoute: typeof AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthStatsRoute: AuthStatsRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  AuthAgentsAgentIdRoute: AuthAgentsAgentIdRoute,
  AuthAgentsNewRoute: AuthAgentsNewRoute,
  AuthContactsContactIdRoute: AuthContactsContactIdRoute,
  AuthContactsNewRoute: AuthContactsNewRoute,
  AuthConversationsNewRoute: AuthConversationsNewRoute,
  AuthIntegrationsMediaPreprocessingRoute:
    AuthIntegrationsMediaPreprocessingRoute,
  AuthAgentsIndexRoute: AuthAgentsIndexRoute,
  AuthContactsIndexRoute: AuthContactsIndexRoute,
  AuthConversationsIndexRoute: AuthConversationsIndexRoute,
  AuthIntegrationsIndexRoute: AuthIntegrationsIndexRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
  AuthIntegrationsInstagramNewRoute: AuthIntegrationsInstagramNewRoute,
  AuthIntegrationsWhatsappNewRoute: AuthIntegrationsWhatsappNewRoute,
  AuthSettingsApiKeysApiKeyIdRoute: AuthSettingsApiKeysApiKeyIdRoute,
  AuthSettingsApiKeysNewRoute: AuthSettingsApiKeysNewRoute,
  AuthSettingsMembersMemberIdRoute: AuthSettingsMembersMemberIdRoute,
  AuthSettingsMembersNewRoute: AuthSettingsMembersNewRoute,
  AuthSettingsOrganizationNewRoute: AuthSettingsOrganizationNewRoute,
  AuthSettingsWebhooksWebhookIdRoute: AuthSettingsWebhooksWebhookIdRoute,
  AuthSettingsWebhooksNewRoute: AuthSettingsWebhooksNewRoute,
  AuthIntegrationsInstagramIndexRoute: AuthIntegrationsInstagramIndexRoute,
  AuthIntegrationsWhatsappIndexRoute: AuthIntegrationsWhatsappIndexRoute,
  AuthSettingsApiKeysIndexRoute: AuthSettingsApiKeysIndexRoute,
  AuthSettingsMembersIndexRoute: AuthSettingsMembersIndexRoute,
  AuthSettingsOrganizationIndexRoute: AuthSettingsOrganizationIndexRoute,
  AuthSettingsWebhooksIndexRoute: AuthSettingsWebhooksIndexRoute,
  AuthIntegrationsInstagramOnboardingTokenIdRoute:
    AuthIntegrationsInstagramOnboardingTokenIdRoute,
  AuthIntegrationsInstagramOnboardingNewRoute:
    AuthIntegrationsInstagramOnboardingNewRoute,
  AuthIntegrationsWhatsappOnboardingTokenIdRoute:
    AuthIntegrationsWhatsappOnboardingTokenIdRoute,
  AuthIntegrationsWhatsappOnboardingNewRoute:
    AuthIntegrationsWhatsappOnboardingNewRoute,
  AuthIntegrationsInstagramOrgAddressIdIndexRoute:
    AuthIntegrationsInstagramOrgAddressIdIndexRoute,
  AuthIntegrationsInstagramOnboardingIndexRoute:
    AuthIntegrationsInstagramOnboardingIndexRoute,
  AuthIntegrationsWhatsappOrgAddressIdIndexRoute:
    AuthIntegrationsWhatsappOrgAddressIdIndexRoute,
  AuthIntegrationsWhatsappOnboardingIndexRoute:
    AuthIntegrationsWhatsappOnboardingIndexRoute,
  AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRoute:
    AuthIntegrationsWhatsappOrgAddressIdTemplatesTemplateIdRoute,
  AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRoute:
    AuthIntegrationsWhatsappOrgAddressIdTemplatesNewRoute,
  AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRoute:
    AuthIntegrationsWhatsappOrgAddressIdTemplatesIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  LoginEmailRoute: LoginEmailRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  OauthInstagramRoute: OauthInstagramRoute,
  OnboardInstagramTokenRoute: OnboardInstagramTokenRoute,
  OnboardInstagramCallbackRoute: OnboardInstagramCallbackRoute,
  OnboardWhatsappTokenRoute: OnboardWhatsappTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
